(() => {
  const LANGUAGE_KEY = "portfolio-language";
  const CHINESE_HOST_HINTS = ["netlify.app"];
  const SKIP_TAGS = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "IFRAME", "VIDEO", "AUDIO", "CANVAS"]);
  const originalText = new WeakMap();
  const originalTitle = document.title;

  const zh = {
    "Yifan Zhu": "朱一帆",
    "YIFAN ZHU": "朱一帆",
    "Work": "项目",
    "Practice": "实践",
    "About": "关于",
    "Contact": "联系",
    "Portfolio": "作品集",
    "Home / About": "首页 / 关于",
    "Home / Practice": "首页 / 实践",
    "Home / Work": "首页 / 项目",
    "Home / Practice / Resource Platform": "首页 / 实践 / 资源平台",
    "Project Hub": "项目导航",
    "All Projects": "全部项目",
    "Choose a Direction": "选择浏览方向",
    "Featured Case Studies": "精选案例",
    "Public Practice Metrics": "公开实践数据",
    "Skills & Methods": "技能与方法",
    "Profile": "个人简介",
    "How I Work": "我的工作方式",
    "CV": "简历",
    "Public Metrics": "公开数据",
    "Challenge": "挑战",
    "Process": "过程",
    "Evidence": "证据",
    "Outcome": "结果",
    "External Links": "外部链接",
    "Practice Structure": "实践结构",
    "All": "全部",
    "Service & Transformation": "服务与转型",
    "Creative Technology": "创意技术",
    "Cultural / Education": "文化 / 教育",
    "Social / Public Innovation": "社会 / 公共创新",
    "Speculative / Critical Interaction": "思辨 / 批判性交互",
    "Service Design / Creative Technology / 3D + AI": "服务设计 / 创意技术 / 3D + AI",
    "Service Systems": "服务系统",
    "Creative Technology": "创意技术",
    "Cultural Learning": "文化学习",
    "Service & Transformation Design": "服务与转型设计",
    "Creative Technology / 3D / AI": "创意技术 / 3D / AI",
    "Cultural & Educational Experience": "文化与教育体验",
    "View Service & Transformation Work": "查看服务与转型项目",
    "View Creative Technology Practice": "查看创意技术实践",
    "View Cultural Experience Projects": "查看文化体验项目",
    "Open all work": "查看全部项目",
    "View evidence page": "查看证据页面",
    "Open full evidence page": "打开完整证据页面",
    "Open RED profile": "打开小红书主页",
    "Open Bilibili profile": "打开 Bilibili 主页",
    "Open Bilibili": "打开 Bilibili",
    "View Douyin work": "查看抖音作品",
    "Visit resource website": "访问资源网站",
    "View resource platform": "查看资源平台",
    "Request CV": "索取简历",
    "View Case Study": "查看案例",
    "View Evidence Page": "查看证据页",
    "View Xiaohongshu / RED": "查看小红书 / RED",
    "View Bilibili": "查看 Bilibili",
    "View Douyin": "查看抖音",
    "Visit Resource Website": "访问资源网站",
    "View Product Case Study": "查看产品案例",
    "View Live Product": "查看在线产品",
    "View live product": "查看在线产品",
    "Open the full product case study": "打开完整产品案例",
    "Resource Website": "资源网站",
    "Xiaohongshu / RED": "小红书 / RED",
    "Bilibili": "Bilibili",
    "Douyin": "抖音",

    "Service & Transformation Designer working with Creative Technology, 3D Visualisation and AI-assisted Prototyping.": "服务与转型设计师，结合创意技术、3D 可视化和 AI 辅助原型进行设计实践。",
    "I translate complex social, cultural and ecological systems into visual, interactive and research-led experiences.": "我将复杂的社会、文化与生态系统转译为可视化、可交互、以研究为基础的体验。",
    "Start from the role, then move into project evidence.": "从求职方向进入，再查看对应的项目证据。",
    "For service design, transformation design, systems thinking and research-led innovation roles.": "适合服务设计、转型设计、系统思维和研究驱动创新方向。",
    "For creative technologist, 3D visualisation, AI-assisted prototyping and digital experience roles.": "适合创意技术、3D 可视化、AI 辅助原型和数字体验方向。",
    "For cultural experience, learning design, social innovation and public engagement roles.": "适合文化体验、学习设计、社会创新和公共参与方向。",
    "The strongest project evidence for recruiters.": "给招聘方快速判断能力的核心项目证据。",
    "Turning Scottish food heritage into an interactive learning journey about service innovation and inclusive hospitality.": "将苏格兰饮食文化转化为关于服务创新与包容性 hospitality 的互动学习旅程。",
    "A future museum-and-park experience translating ecological rhythms in Pollok Country Park into visitor action.": "一个面向未来的博物馆与公园体验，将 Pollok Country Park 的生态节律转化为游客的观察、反思与行动。",
    "A public-facing creative technology practice across Douyin, Bilibili, Xiaohongshu and a personal resource website.": "围绕抖音、Bilibili、小红书和个人资源网站展开的公开创意技术实践。",
    "Smart whale monitoring and echo enhancement, translated into an interactive public education installation.": "将鲸类声学监测与回声增强概念转译为互动公共教育装置。",
    "Public 3D / AI Design Practice": "公开 3D / AI 设计实践",
    "Alongside academic service and transformation design projects, I run a public-facing 3D and AI-assisted creative practice across Douyin, Xiaohongshu, Bilibili and a personal resource website.": "在学术服务与转型设计项目之外，我也在抖音、小红书、Bilibili 和个人资源网站上持续经营公开的 3D 与 AI 辅助创作实践。",
    "likes & collects on Xiaohongshu / RED": "小红书点赞与收藏",
    "total views on Bilibili": "Bilibili 总播放量",
    "54K+ likes on one original Blender visual reel": "单条原创 Blender 视觉短片获得 5.4 万+点赞",
    "free resource downloads / claims": "免费资源下载 / 领取",
    "resource users": "资源用户",
    "A mixed toolkit for research-led digital service work.": "用于研究驱动数字服务工作的复合工具箱。",
    "Research & Strategy": "研究与策略",
    "Desk research, field observation, stakeholder mapping, service blueprinting, systems framing and insight synthesis.": "桌面研究、田野观察、利益相关者地图、服务蓝图、系统框架与洞察综合。",
    "Experience Design": "体验设计",
    "Learning journeys, public engagement, phygital interaction, prototyping, testing and reflective iteration.": "学习旅程、公共参与、虚实融合交互、原型、测试与反思迭代。",
    "Blender, Unity, Arduino, TouchDesigner, Python, AI-assisted workflows and visual communication.": "Blender、Unity、Arduino、TouchDesigner、Python、AI 辅助流程与视觉传达。",
    "Open to service design, transformation design and creative technology opportunities.": "开放服务设计、转型设计和创意技术相关机会。",

    "Work organised by role evidence.": "按岗位能力证据组织的项目。",
    "A scannable project hub for service design, transformation design, creative technology, cultural learning and social innovation roles.": "一个方便快速浏览的项目导航，覆盖服务设计、转型设计、创意技术、文化学习和社会创新方向。",
    "Open a case study from the evidence you need.": "根据你需要看的能力证据打开对应案例。",
    "Service & Transformation / Cultural Ecology": "服务与转型 / 文化生态",
    "Cultural / Education / Service Innovation": "文化 / 教育 / 服务创新",
    "Creative Technology / Public Learning": "创意技术 / 公开学习",
    "Environmental Technology / Speculative System": "环境技术 / 思辨系统",
    "Creative Technology / Critical AI": "创意技术 / 批判性 AI",
    "Service & Transformation / Urban Biodiversity": "服务与转型 / 城市生物多样性",
    "Social / Public Innovation / Cultural Experience": "社会 / 公共创新 / 文化体验",
    "A cultural service learning prototype connecting Scottish tea culture with service innovation and inclusive hospitality.": "一个文化服务学习原型，将苏格兰茶文化与服务创新、包容性 hospitality 连接起来。",
    "A public-facing practice across Douyin, Bilibili, Xiaohongshu and a resource website for 3D, Blender and AI-assisted workflows.": "一个面向公众的实践，围绕抖音、Bilibili、小红书和资源网站发布 3D、Blender 与 AI 辅助流程内容。",
    "An acoustic monitoring and public interaction concept that makes underwater noise disruption more legible.": "一个声学监测与公共互动概念，让水下噪音干扰问题更容易被公众理解。",
    "A participatory interaction experiment using speech, image search and visualization to question colour stereotypes.": "一个使用语音、图像搜索和可视化来质疑颜色刻板印象的参与式交互实验。",
    "A city-scale AR service concept for reconnecting fragmented urban biodiversity through seed cards and public participation.": "一个城市尺度 AR 服务概念，通过种子卡片和公众参与重新连接碎片化城市生物多样性。",
    "A social pack and board-game system for helping Chinese international students connect through low-pressure interaction.": "一套社交卡包与桌游系统，帮助中国留学生通过低压力互动建立连接。",

    "Creative Technology & Visual Practice": "创意技术与视觉实践",
    "3D visualisation, AI-assisted prototyping and public learning resources.": "3D 可视化、AI 辅助原型与公开学习资源。",
    "This page collects independent visual and technical practice that sits beside my research-led case studies. It shows craft, tool fluency, public teaching output and the way I use digital workflows to make ideas easier to see and share.": "这一页汇集了我在研究型案例之外的独立视觉与技术实践，展示手工能力、工具熟练度、公开教学输出，以及我如何用数字流程让想法更容易被看见和分享。",
    "Three evidence areas for creative technology roles.": "面向创意技术岗位的三类证据。",
    "3D Visualisation / Blender Craft": "3D 可视化 / Blender 手工能力",
    "Manual modeling, material atmosphere, lighting and cinematic visual prototyping.": "手动建模、材质氛围、灯光与电影感视觉原型。",
    "AI-assisted Web & Creative Pipeline": "AI 辅助网页与创作流程",
    "AI-assisted website building, AI-generated character and animation workflows.": "AI 辅助网站搭建、AI 生成人物与动画流程。",
    "Public Learning & Resource Platform": "公开学习与资源平台",
    "Public tutorials, free resource downloads / claims and creator-platform evidence.": "公开教程、免费资源下载 / 领取与创作者平台数据证据。",
    "Codex / AI-assisted web prototype": "Codex / AI 辅助网页原型",
    "AI creative pipeline collaboration": "AI 创作流程合作",
    "Manual 3D modeling and visual prototyping.": "手动 3D 建模与视觉原型。",
    "AI-supported workflows used as prototyping material.": "将 AI 支持流程作为原型材料。",
    "Independent public practice with measurable engagement.": "有可衡量互动数据的独立公开实践。",
    "Main visual reel": "主要视觉合集",
    "Manual modeling study 01": "手动建模练习 01",
    "Manual modeling study 02": "手动建模练习 02",
    "Manual modeling study 03": "手动建模练习 03",
    "Self-made 3D modeling and visual-build evidence.": "自主完成的 3D 建模与视觉搭建证据。",
    "Additional Blender-based modeling and visual prototyping work.": "更多基于 Blender 的建模和视觉原型实践。",
    "Further production range and visual control.": "进一步展示制作范围和视觉控制能力。",
    "A personal website prototype and teaching-content showcase built through an AI-assisted workflow.": "通过 AI 辅助流程搭建的个人网站原型与教学内容展示。",
    "AI-generated character and animation workflow produced for a Hyper3D collaboration.": "为 Hyper3D 合作制作的 AI 生成人物与动画流程视频。",

    "Public Design-Learning Platform / Digital Resource Practice": "公开设计学习平台 / 数字资源实践",
    "Independent 3D & AI Resource Platform": "独立 3D 与 AI 资源平台",
    "Role": "角色",
    "Platforms": "平台",
    "Focus": "重点",
    "Output": "产出",
    "Independent creator, 3D visualisation designer, tutorial producer and resource platform operator": "独立创作者、3D 可视化设计师、教程制作人与资源平台运营者",
    "Douyin, Xiaohongshu / RED, Bilibili and personal resource website": "抖音、小红书 / RED、Bilibili 与个人资源网站",
    "Blender, GIS, AI-assisted workflows, visual prototyping and reusable learning files": "Blender、GIS、AI 辅助流程、视觉原型与可复用学习文件",
    "Tutorial videos, design-process posts, free project files and resource distribution": "教程视频、设计过程帖、免费项目文件与资源分发",
    "Measurable engagement around 3D and AI-assisted learning resources.": "围绕 3D 与 AI 辅助学习资源的可衡量互动数据。",
    "likes & collects": "点赞与收藏",
    "total views": "总播放量",
    "free digital resource downloads / claims": "免费数字资源下载 / 领取",
    "Making technical workflows easier to learn, reproduce and adapt.": "让技术流程更容易学习、复现和改造。",
    "From workflow testing to public resource distribution.": "从流程测试到公开资源分发。",
    "What this independent practice demonstrates.": "这项独立实践证明了什么。",
    "Public communication": "公开传播",
    "Reusable resource design": "可复用资源设计",
    "Creative technology fluency": "创意技术熟练度",
    "Independent initiative": "独立主动性",
    "A public-facing design practice with evidence beyond academic work.": "一个有学术项目之外证据的公开设计实践。",
    "Verify the public platform work.": "验证公开平台实践。",
    "Original Blender visual reel showcasing two years of visual work.": "展示两年视觉实践的原创 Blender 视觉短片。",
    "Visual design, Blender and AI workflow posts.": "视觉设计、Blender 与 AI 流程内容。",
    "Blender tutorials, 3D workflow videos and design-process content.": "Blender 教程、3D 流程视频和设计过程内容。",
    "Free Blender project files, 3D scene assets and workflow resources.": "免费 Blender 项目文件、3D 场景资产与工作流资源。",

    "Commercial Product": "商业化产品",
    "From a repeated production problem to a released Blender tool.": "从重复出现的制作问题，到正式发布的 Blender 工具。",
    "Independently developed / Publicly released": "独立开发 / 公开发布",
    "I designed, developed, tested and commercially released a Blender add-on that packages a node-heavy holographic projection workflow into a configurable creator tool.": "我独立完成了一款 Blender 插件的设计、开发、测试与商业化发布，将节点繁复的全息投影流程封装为可配置的创作者工具。",
    "Independent product development / Blender add-on": "独立产品开发 / Blender 插件",
    "An independently developed and commercially released Blender add-on that turns a complex holographic projection workflow into a reusable creator tool.": "一款独立开发并商业化发布的 Blender 插件，将复杂的全息投影流程转化为可复用的创作者工具。",
    "Proof: end-to-end development, public product listing, community launch and owned distribution": "证据：全流程开发、公开产品页面、社区发布与自营渠道交付",
    "Independent Software Product / Creative Technology": "独立软件产品 / 创意技术",
    "An independently developed and commercially released Blender add-on for creating configurable holographic projection effects.": "一款独立开发并商业化发布、用于快速创建可配置全息投影效果的 Blender 插件。",
    "Capability proof: product strategy, add-on development, UX, testing, documentation and multi-channel launch.": "能力证据：产品策略、插件开发、交互、测试、文档与多渠道发布。",

    "Home / Work / Cyber Projection Toolkit": "首页 / 项目 / Cyber Projection Toolkit",
    "Project Brief": "项目简报",
    "Launched Commercial Product / Blender Add-on": "已上线商业产品 / Blender 插件",
    "Launched commercial product / Blender add-on": "已上线商业产品 / Blender 插件",
    "A launched commercial Blender add-on shaped by real creator workflow evidence.": "从真实创作需求出发，独立开发并上线的商业 Blender 插件。",
    "Status": "状态",
    "Live commercial digital product; independently developed, published and continuously iterated": "已上线商业数字产品；独立完成开发、发布并持续迭代",
    "3D visual designers, motion-image creators and Blender learning users": "3D 视觉设计师、动态影像创作者与 Blender 学习用户",
    "Product system": "产品系统",
    "Image / video input, procedural glitch effects and centralised shader controls": "图片 / 视频输入、程序化故障效果与集中式着色控制",
    "End-to-end role": "全流程职责",
    "Product definition, UX, parameter logic, add-on development, testing, documentation, launch and support": "产品定义、用户体验、参数逻辑、插件开发、测试、文档、发布与支持",
    "Creator ecosystem": "创作者生态",
    "590K+ related-content views, 74.6K+ likes / saves, 1.1K+ resource deliveries and 460+ platform users": "相关内容累计 59 万+播放、7.46 万+点赞 / 收藏、1,100+次资源交付及 460+平台用户",
    "An independently developed and commercially released creator tool built from recurring Blender workflow problems and real audience evidence.": "针对 Blender 创作中反复遇到的问题，结合真实用户反馈，独立开发并商业化发布的创作工具。",
    "Product proof: end-to-end development, user-informed iteration, public product listing, owned distribution and support.": "产品证据：全流程开发、用户反馈驱动迭代、公开商品页、自营交付与支持。",
    "View Live Product Case": "查看已上线产品案例",
    "An independently developed and commercially released creator tool shaped by workflow evidence, testing and real platform users.": "一款由工作流证据、测试和真实平台用户共同驱动，独立开发并商业发布的创作者工具。",
    "Proof: product definition, UX, development, testing, documentation, launch and support": "证据：产品定义、用户体验、开发、测试、文档、发布与支持",
    "Independent Software Product / Blender Add-on": "独立软件产品 / Blender 插件",
    "An independently developed and commercially released Blender add-on that turns a complex holographic projection workflow into a reusable, configurable tool for 3D artists and visual creators.": "一款独立开发并商业化发布的 Blender 插件，将复杂的全息投影流程转化为面向 3D 艺术家与视觉创作者的可复用、可配置工具。",
    "Independent developer, product owner and commercial publisher": "独立开发者、产品负责人及商业发行者",
    "Product": "产品",
    "Blender add-on for image and video projection effects": "用于图片与视频投影效果的 Blender 插件",
    "Release": "发布",
    "Public commercial launch across an owned storefront and a Blender community channel": "通过自营商店与 Blender 社区渠道完成公开商业化发布",
    "Delivery": "交付",
    "Add-on package, demo file, demo video, sample media and README documentation": "插件安装包、演示工程、演示视频、示例素材及 README 文档",
    "Why I Built It": "开发动机",
    "I found a production bottleneck and turned it into a repeatable product.": "我发现了一个制作瓶颈，并将解决方案转化为可复用的产品。",
    "Building a holographic projection manually meant recreating the same plane, media nodes, shader logic, animation controls and distortion settings for every new asset. The technical setup was slow, easy to break and distracted from the visual decision.": "手动制作全息投影意味着每更换一次素材，都要重新搭建平面、媒体节点、着色器逻辑、动画控制和失真参数。整个技术流程耗时、容易出错，也让创作者难以专注于视觉判断。",
    "Requirement evidence": "需求证据",
    "I reviewed recurring questions in creator comments, resource-claim feedback and technical-support records to define the highest-friction workflow problems before structuring the add-on.": "我通过创作者评论中的高频问题、资源领取反馈与技术支持记录识别工作流中的主要摩擦点，并据此定义插件结构。",
    "01 / Repeated setup": "01 / 重复搭建",
    "Every scene started from zero.": "每个场景都要从零开始。",
    "Artists had to rebuild a multi-step node and material structure before they could judge the image.": "创作者必须先重建多步骤节点与材质结构，之后才能真正判断画面效果。",
    "02 / Slow iteration": "02 / 迭代缓慢",
    "Small changes required technical editing.": "微小调整也需要技术操作。",
    "Glitch timing, colour and media replacement were scattered across the workflow instead of controlled from one place.": "故障节奏、颜色和媒体替换分散在不同环节，无法从一个界面集中控制。",
    "03 / Fragile reuse": "03 / 复用不稳定",
    "Duplicates could affect one another.": "复制对象可能彼此影响。",
    "Shared materials made it difficult to build several independent projections in the same production scene.": "共享材质使多个投影难以在同一制作场景中保持独立。",
    "Product response": "产品回应",
    "Source media → one-click projection → centralised controls → independent variations": "源媒体 → 一键生成投影 → 集中控制 → 独立变体",
    "The toolkit packages the repeated technical layer into a creator-facing workflow, so visual direction becomes the main task.": "插件将重复的技术层封装为面向创作者的工作流，让视觉方向重新成为核心任务。",
    "Repeated node work was slowing down the creative decision.": "重复的节点搭建正在拖慢真正的创意决策。",
    "Holographic projection effects often require artists to rebuild layered materials, animation controls and distortion logic for every scene. I developed the toolkit to package that repeated technical setup into a faster workflow, allowing creators to focus on image choice, timing, colour and atmosphere.": "全息投影效果往往要求创作者为每个场景重新搭建多层材质、动画控制和失真逻辑。我开发这套工具，将重复的技术设置封装为更高效的工作流，让创作者把注意力放回画面选择、节奏、色彩与氛围。",
    "End-to-End Ownership": "全流程负责",
    "One product, independently taken from workflow research to public release.": "独立完成从工作流研究到公开发布的完整产品过程。",
    "Feature Demonstration": "功能演示",
    "See the add-on working inside a real Blender scene.": "直接观看插件在真实 Blender 场景中的工作流程。",
    "This published walkthrough demonstrates the one-click material setup, image and video replacement workflow, and the centralised visual controls used to shape the final projection effect.": "这段公开发布的演示展示了一键材质设置、图片与视频替换流程，以及用于塑造最终投影效果的集中式视觉控制。",
    "English tutorial · 1 min 28 sec · Blender workflow": "英文教程 · 1 分 28 秒 · Blender 工作流程",
    "View live product ↗": "查看在线产品 ↗",
    "Core Feature System": "核心功能系统",
    "The manual workflow is compressed into six creator-facing functions.": "将复杂的手动流程压缩为六项面向创作者的核心功能。",
    "Each function removes a specific production barrier while keeping the final look adjustable inside Blender.": "每项功能都对应一个具体制作障碍，同时保留 Blender 内对最终视觉效果的完整调整能力。",
    "01 / Create": "01 / 创建",
    "Start from an image or video": "从图片或视频开始",
    "Select a source file and create the projection directly from the add-on sidebar.": "选择源文件，即可从插件侧栏直接创建投影。",
    "02 / Generate": "02 / 自动生成",
    "Build the technical system automatically": "自动搭建完整技术系统",
    "The projection plane, material and media connection are generated as one production-ready setup.": "投影平面、材质与媒体连接会自动生成为可直接制作的完整系统。",
    "03 / Presets": "03 / 预设",
    "Move quickly between visual directions": "快速探索不同视觉方向",
    "Built-in interference, scan, RGB and combined glitch presets shorten early exploration.": "内置干扰、扫描、RGB 与组合故障预设，加快早期视觉探索。",
    "04 / Animate": "04 / 动画",
    "Control procedural glitch timing": "控制程序化故障节奏",
    "Frame range, count, seed and intensity expose the motion system without reopening the node graph.": "通过帧范围、次数、随机种子与强度控制动画，无需重新进入节点系统。",
    "05 / Art direct": "05 / 视觉控制",
    "Tune colour, depth and visibility": "调整颜色、深度与可见度",
    "Offset, brightness, tint and original-colour balance are consolidated for faster visual decisions.": "将偏移、亮度、色调和原始色彩平衡集中管理，加快视觉决策。",
    "06 / Reuse": "06 / 复用",
    "Replace media without rebuilding": "无需重建即可替换媒体",
    "Swap the current image or video while preserving the projection system and its controls.": "在保留投影系统与全部控制项的同时替换当前图片或视频。",
    "Identified a repeatable production problem through personal Blender practice": "从个人 Blender 实践中识别可重复解决的制作问题",
    "Designed the add-on structure and consolidated shader controls": "设计插件结构并整合着色器控制项",
    "Developed and tested image, video, glitch, RGB split, scanline and flicker functions": "开发并测试图片、视频、故障、RGB 色差、扫描线与闪烁功能",
    "Built presets, demo scenes and installation documentation": "制作预设、演示场景与安装文档",
    "Created the product identity, launch visuals and feature demonstration": "完成产品识别、发布视觉与功能演示",
    "Published the commercial product through an owned storefront and Blender community channel": "通过自营商店与 Blender 社区渠道发布商业产品",
    "Product in Use": "产品实测",
    "Production Results": "制作结果",
    "One system supports different media and distinct visual directions.": "同一套系统支持不同媒体与多种视觉方向。",
    "A creator-facing interface, tested through real production scenes.": "面向创作者的界面，并通过真实制作场景完成测试。",
    "Configurable glitch, colour and projection controls inside Blender.": "Blender 内可配置的故障、色彩与投影控制。",
    "The same system adapted into a distinct amber visual direction.": "同一系统可快速调整为不同的琥珀色视觉方向。",
    "Source media used to test image and video replacement workflows.": "用于测试图片与视频替换流程的源素材。",
    "Launch Context": "发布背景",
    "Testing & Iteration": "测试与迭代",
    "I tested the add-on as a production tool, not only as working code.": "我把插件作为真实制作工具进行测试，而不只是验证代码能够运行。",
    "The testing process focused on repeatability: whether the system stayed controllable when media changed, settings became more complex and multiple projections shared one scene.": "测试重点是可重复性：当媒体发生变化、参数更加复杂，或同一场景中出现多个投影时，系统能否继续保持稳定和可控。",
    "Issue found": "发现问题",
    "Duplicated objects shared the same material": "复制对象共享同一材质",
    "Editing one copy could unintentionally change every projection using that material.": "修改其中一个副本，可能意外改变所有使用该材质的投影。",
    "Iteration": "功能迭代",
    "Independent Material and Auto-Disconnect": "独立材质与自动断开",
    "I added controls that create an independent material copy, making variation safer and faster.": "我增加了创建独立材质副本的控制，使视觉变体的制作更安全、更快速。",
    "Regression check": "回归验证",
    "Multiple effects in one production scene": "同一制作场景中的多个独立效果",
    "Final testing confirmed that each projection could use its own media, colour and settings without affecting the others.": "最终测试确认每个投影都可以使用独立的媒体、颜色与设置，且不会影响其他对象。",
    "Input coverage": "输入覆盖",
    "User-task coverage": "用户任务覆盖",
    "5 key tasks": "5 项关键任务",
    "Installation, media import, parameter understanding, effect adjustment and animation output.": "安装、媒体导入、参数理解、效果调节与动画输出。",
    "Image + video": "图片 + 视频",
    "Checked creation and replacement across both supported media types.": "验证两种媒体类型的创建与替换流程。",
    "Control coverage": "控制覆盖",
    "Preset + custom": "预设 + 自定义",
    "Tested fast preset selection and detailed parameter-level adjustment.": "测试快速预设选择与细节参数调整。",
    "Scene coverage": "场景覆盖",
    "Single + multiple": "单个 + 多个",
    "Validated isolated projections and several independently art-directed copies.": "验证单独投影及多个独立视觉控制副本。",
    "Delivery coverage": "交付覆盖",
    "Add-on + demo + guide": "插件 + 演示 + 文档",
    "Packaged installation, example scenes and documentation for use outside my own setup.": "将安装包、示例场景与说明文档完整打包，使产品可以脱离个人环境使用。",
    "Built for a real creator audience, not a hypothetical persona.": "面向真实创作者群体，而非假设用户画像。",
    "The add-on launched through an owned resource platform already used by 460+ creators and supported by 1.1K+ digital-resource deliveries. These figures establish the real audience around the product without presenting every platform user as a plugin customer.": "插件通过自营数字资源平台发布；该平台已覆盖 460+ 创作者，并完成 1.1K+ 次数字资源交付。这些数据证明产品建立在真实受众基础上，但不将每位平台用户表述为插件购买者。",
    "Released into an existing public creator-resource ecosystem.": "发布到已有真实受众的公开创作者资源生态中。",
    "The figures below describe the wider platform audience that informed the product opportunity, rather than claiming they are all plugin customers.": "以下数据代表为产品机会提供依据的整体平台受众，并不将其全部表述为插件购买用户。",
    "Platform users": "平台用户",
    "People reached through the wider Boywithdoughnut digital resource platform.": "通过 Boywithdoughnut 数字资源平台累计覆盖的用户。",
    "Open owned storefront": "打开自营商店",
    "Resource delivery": "资源交付",
    "Digital resource downloads and claims across the existing creator ecosystem.": "现有创作者生态中的数字资源下载与领取。",
    "View platform evidence": "查看平台证据",
    "Publishing channels": "发布渠道",
    "Owned commerce and delivery through Huotan, with public discovery through the Blender community.": "由货摊网承接自营交易与交付，并通过 Blender 社区获得公开曝光。",
    "Open community launch": "打开社区发布页",
    "Product ownership": "产品负责范围",
    "End-to-end": "全流程",
    "Research, development, testing, product design, documentation, launch and support.": "研究、开发、测试、产品设计、文档、发布与支持。",
    "Commercialisation": "商业化",
    "A direct path from community discovery to owned product delivery.": "从社区发现到自营产品交付的直接路径。",
    "I structured the launch as a simple product funnel: feature demonstration and community discovery lead to a dedicated product page, which handles purchase, file delivery and user contact. This creates a verifiable commercial pathway without separating the tool from the broader creative practice that generated it.": "我将发布过程设计为清晰的产品路径：功能演示和社区曝光导向独立商品页面，由该页面承接购买、文件交付与用户联系。这形成了可验证的商业闭环，同时保留插件与其创作实践背景之间的联系。",
    "Discover": "发现产品",
    "Feature content and a public Blender community listing introduce the problem and result.": "通过功能内容与公开 Blender 社区页面展示问题和最终效果。",
    "Evaluate": "了解与评估",
    "The English tutorial, interface screenshots and feature breakdown explain how the product works.": "通过英文教程、界面截图和功能拆解说明产品如何工作。",
    "Acquire": "购买与获取",
    "An owned storefront handles the product page, transaction and digital-file delivery.": "由自营商店承接产品介绍、交易与数字文件交付。",
    "Use & extend": "使用与扩展",
    "The add-on, demonstration scene, sample media and README support first use and adaptation.": "插件、演示场景、示例媒体与 README 支持首次使用和后续调整。",
    "Public Evidence": "公开证据",
    "The product and launch can be verified online.": "产品及其发布过程均可在线验证。",
    "Live Product": "在线产品",
    "Commercial product page, feature list, price and delivery package.": "包含功能、价格及交付内容的商业产品页面。",
    "Community Launch": "社区发布",
    "Public Blender community release page linking back to the owned storefront.": "公开的 Blender 社区发布页面，并导向自营商店。",
    "Feature Demo": "功能演示",
    "Public demonstration of the add-on and its projection workflow.": "公开展示插件功能及投影工作流程。",
    "Previous: Resource Platform": "上一个：资源平台",
    "Next: Biodiversity Clock": "下一个：生物多样性时钟",

    "Institutional Collaboration / Transformation Design": "机构合作 / 转型设计",
    "A place-based experience innovation collaboration with Glasgow City Council and Glasgow Life.": "与 Glasgow City Council 及 Glasgow Life 开展的场所型体验创新合作。",
    "Partner organisations": "合作机构",
    "Glasgow City Council × Glasgow Life": "Glasgow City Council × Glasgow Life",
    "Live context": "真实场域",
    "Pollok Country Park and The Burrell Collection, South Glasgow": "格拉斯哥南部的 Pollok Country Park 与 The Burrell Collection",
    "Experience research and future-experience design": "体验研究与未来体验设计",
    "Methods": "方法",
    "Field observation, stakeholder participation, visitor research, systems thinking and Three Horizons": "现场观察、利益相关者参与、游客研究、系统思维与 Three Horizons",
    "Biodiversity Clock experience connecting species activity, environmental change and public participation": "连接物种活动、环境变化与公众参与的“生物多样性时钟”体验方案",
    "Developed in collaboration with The Burrell Collection and Pollok Country Park stakeholders, this place-based transformation design project translates ecological rhythms into a museum-and-park experience that invites visitors to notice, understand and participate in multi-species coexistence.": "本项目与 The Burrell Collection 及 Pollok Country Park 相关团队合作开展，将生态节律转译为连接博物馆与公园的体验，引导游客观察、理解并参与多物种共生。",
    "The work was grounded in stakeholder meetings, on-site research and direct observation across the museum and park. Rather than creating a fictional nature experience, the team responded to an operating cultural institution, a living ecological site and the visitor behaviours connecting them.": "项目建立在利益相关者会议、博物馆与公园的现场调研及直接观察之上。团队回应的是一个真实运营的文化机构、持续变化的生态场地，以及连接二者的游客行为，而非虚构的自然体验。",
    "Institutional Context": "机构背景",
    "A museum–park collaboration grounded in South Glasgow.": "扎根格拉斯哥南部的博物馆与公园合作。",
    "The Burrell Collection is a Glasgow Life museum located inside Pollok Country Park. The collaboration connected institutional priorities, visitor experience and the park's living ecology through meetings, field inquiry and service design.": "The Burrell Collection 是由 Glasgow Life 运营、坐落于 Pollok Country Park 内的博物馆。本次合作通过会议、实地调研与服务设计，将机构目标、游客体验和公园生态联系起来。",
    "A Glasgow Life museum embedded within Pollok Country Park. Photo: Anthony O'Neil / Geograph, CC BY-SA 2.0.": "位于 Pollok Country Park 内、由 Glasgow Life 运营的博物馆。摄影：Anthony O'Neil / Geograph，CC BY-SA 2.0。",
    "The live ecological and visitor context for the project. Photo: Osama Shukir Muhammed Amin, CC BY-SA 4.0.": "本项目真实的生态与游客活动场域。摄影：Osama Shukir Muhammed Amin，CC BY-SA 4.0。",
    "Partner context": "合作方背景",
    "A civic museum of approximately 9,000 objects, managed by Glasgow Life and situated within the park landscape.": "一座由 Glasgow Life 运营、拥有约 9,000 件藏品并坐落于公园景观中的公共博物馆。",
    "Working process": "合作过程",
    "Institutional meetings + field research": "机构会议 + 实地调研",
    "The team engaged with institutional representatives, researchers and site stakeholders, then translated field evidence into a service and experience proposal.": "团队与机构代表、调查人员及场地利益相关者进行沟通，并将现场证据转化为服务与体验设计方案。",
    "An AR urban-ecology product connecting spatial data, seed cards and public participation.": "一款连接空间数据、实体种子卡与公众参与的 AR 城市生态产品。",
    "March–July 2024": "2024年3月—7月",
    "Product design, UI/UX design and AR service-system design": "产品设计、UI/UX 设计与 AR 服务系统设计",
    "Product scope": "产品范围",
    "Information architecture, user flow, low- and high-fidelity UI, service blueprint and AR experience": "信息架构、用户流程、低保真与高保真界面、服务蓝图及 AR 体验",
    "Technical system": "技术系统",
    "ENVI, ArcGIS / NDVI, Blender and Unity": "ENVI、ArcGIS / NDVI、Blender 与 Unity",
    "Six-module journey from seed access and AR planting to ecological feedback, contribution records and community participation": "由种子获取、AR 种植、生态反馈、贡献记录及社区参与组成的六模块体验旅程",
    "An exhibited interactive system translating underwater acoustic disruption into a public experience.": "一套将水下声学干扰转化为公众体验并完成公开展出的交互系统。",
    "Publicly exhibited in Beijing on 17 August 2024": "2024年8月17日在北京完成公开展出",
    "Smart-product design, creative technology and interaction design": "智能产品设计、创意技术与交互设计",
    "Research validation": "研究验证",
    "MFCC, Chroma and Mel Spectrogram acoustic-feature experiments": "MFCC、Chroma 与 Mel Spectrogram 声学特征实验",
    "Python, Arduino, ultrasonic sensing, TouchDesigner and Blender": "Python、Arduino、超声波感知、TouchDesigner 与 Blender",
    "Public outcome": "公众成果",
    "Working exhibition interaction, live demonstrations and direct audience engagement": "可运行的展览互动、现场演示与直接观众参与",
    "A participatory AI interaction translating social input into visible machine memory.": "一项将社会输入转化为可见机器记忆的参与式 AI 交互。",
    "AI interaction product experiment / critical creative technology": "AI 交互产品实验 / 批判性创意技术",
    "AI interaction product design, AI UX and creative technology": "AI 交互产品设计、AI UX 与创意技术",
    "Information pipeline": "信息流程",
    "Speech input → Vosk recognition → keyword extraction → image retrieval → colour processing → Blender visualisation": "语音输入 → Vosk 识别 → 关键词提取 → 图像检索 → 色彩处理 → Blender 可视化",
    "Participation model": "参与机制",
    "Human-in-the-loop discussions around blue, green and pink": "围绕蓝、绿、粉三种颜色展开的 Human-in-the-loop 讨论",
    "Working prototype connecting Arduino, Python, Vosk and Blender": "连接 Arduino、Python、Vosk 与 Blender 的可运行原型",
    "Institutional Collaboration / Place-based Transformation Design": "机构合作 / 场所型转型设计",
    "Stakeholder meetings with The Burrell Collection and Pollok Country Park; field research; visitor and ecological inquiry.": "与 The Burrell Collection、Pollok Country Park 相关方开展会议，并进行现场、游客与生态调研。",
    "Service design researcher and experience strategist; responsible for research synthesis, concept logic, visual prototyping and final communication.": "服务设计研究与体验策略；负责研究综合、概念逻辑、视觉原型及最终沟通。",

    "Designing between systems, culture and creative technology.": "在系统、文化与创意技术之间进行设计。",
    "I am a service and transformation designer with a creative technology edge. My work translates complex ecological, cultural and social systems into visual, interactive and research-led experiences.": "我是一名带有创意技术背景的服务与转型设计师。我的作品将复杂的生态、文化与社会系统转译为可视化、可交互、以研究为基础的体验。",
    "Research-led framing": "研究驱动的框架搭建",
    "I use desk research, field observation, stakeholder mapping and synthesis to turn broad topics into focused design opportunities.": "我通过桌面研究、田野观察、利益相关者地图与综合分析，把宽泛主题转化为清晰的设计机会。",
    "Experience prototyping": "体验原型",
    "I build tangible, visual and interactive prototypes that make abstract systems easier to test, explain and discuss.": "我搭建实体、视觉和交互原型，让抽象系统更容易被测试、解释和讨论。",
    "Creative technology practice": "创意技术实践",
    "I use Blender, AI-assisted workflows, physical computing and web-based prototypes as tools for exploration and communication.": "我使用 Blender、AI 辅助流程、物理计算和网页原型作为探索与沟通工具。",
    "CV available upon request.": "可按需提供简历。",
    "For applications, I can share the most relevant CV version depending on whether the role focuses on service transformation, creative technology, 3D visualisation or AI-assisted prototyping.": "针对不同申请方向，我可以提供更匹配的简历版本，例如服务转型、创意技术、3D 可视化或 AI 辅助原型方向。",

    "Home / Work / Scone Through Time": "首页 / 项目 / 司康时光",
    "Cultural Service Learning Prototype": "文化服务学习原型",
    "A digital learning journey for service innovation and inclusive hospitality.": "一个面向服务创新与包容性 hospitality 的数字学习旅程。",
    "A cultural service learning prototype that uses Scottish tea culture, object-led storytelling and interactive micro-modules to help young learners connect cultural heritage with service innovation and inclusive hospitality.": "一个文化服务学习原型，通过苏格兰茶文化、物件引导叙事和互动微课程模块，帮助年轻学习者把文化遗产与服务创新、包容性 hospitality 连接起来。",
    "Scone Through Time was developed in response to a real educational and cultural learning context. The project explored how Scottish afternoon tea and scone culture could become a low-barrier learning experience for secondary, ASN and hospitality learners.": "《司康时光》回应真实的教育与文化学习语境，探索苏格兰下午茶和司康文化如何成为面向中学生、ASN 学习者与 hospitality 学生的低门槛学习体验。",
    "Project Type": "项目类型",
    "Real-world grounding": "现实语境",
    "Audience": "受众",
    "Cultural Service Learning Prototype / Educational Service Experience": "文化服务学习原型 / 教育服务体验",
    "Scottish afternoon tea and scone culture; secondary / ASN / hospitality learner needs; peer-tested classroom-style prototype.": "苏格兰下午茶与司康文化；中学 / ASN / hospitality 学习者需求；经过同伴测试的课堂式原型。",
    "Secondary school learners, ASN learners and hospitality students": "中学生、ASN 学习者与 hospitality 学生",
    "Team member; contributed to research filtering, ideation, testing, storytelling and learning experience development.": "团队成员；参与研究筛选、概念生成、测试、叙事和学习体验开发。",
    "Three stop-motion micro-learning modules, interactive learning prompts and tea bag business model simulation.": "三个定格动画微学习模块、互动学习提示和茶包商业模式模拟。",
    "In this case study": "本案例结构",
    "A research-to-learning pivot.": "从研究转向学习体验的关键转折。",
    "01 Context & Challenge": "01 背景与挑战",
    "02 Research Filtering": "02 研究筛选",
    "03 Ideation & Testing": "03 构思与测试",
    "04 Final Learning Experience": "04 最终学习体验",
    "05 Potential Educational Value": "05 潜在教育价值",
    "Everyday cultural objects became a way into service learning.": "日常文化物件成为进入服务学习的入口。",
    "The challenge was not to display cultural history.": "挑战不是展示文化历史。",
    "Three learner groups shaped the experience structure.": "三类学习者塑造了体验结构。",
    "Secondary school learners": "中学生",
    "ASN learners": "ASN 学习者",
    "Hospitality students": "Hospitality 学生",
    "Need concrete stories and clear examples rather than long explanatory text.": "需要具体故事和清晰案例，而不是长篇解释文字。",
    "Need highly visual, chunked and low-barrier content that supports different learning access needs.": "需要高度视觉化、分段清晰、低门槛的内容，以支持不同学习进入方式。",
    "Need to connect heritage, service experience and business skills in a practical way.": "需要以实践方式连接文化遗产、服务体验和商业技能。",
    "Too much material, not enough teachable story.": "材料太多，但可教学的故事不够清晰。",
    "What we did": "我们做了什么",
    "What we found": "我们发现了什么",
    "Why it mattered": "为什么重要",
    "Design decision": "设计决策",
    "Explored broad Scottish tea, food heritage, tourism and hospitality sources.": "广泛研究苏格兰茶文化、食物遗产、旅游与 hospitality 资料。",
    "The research field was fragmented and difficult to turn into a focused learning journey.": "研究材料非常碎片化，难以直接转化为聚焦的学习旅程。",
    "Young learners need a teachable story, not a dense archive of disconnected facts.": "年轻学习者需要可教学的故事，而不是大量互不连接的事实档案。",
    "Simplify the project around recognisable cultural objects and clear learning moments.": "围绕可识别的文化物件和清晰学习时刻简化项目。",
    "Research was filtered through time, people and item.": "研究通过时间、人群和物件三个维度被筛选。",
    "Fragmented tea / food culture research": "碎片化茶 / 食物文化研究",
    "Time / People / Item": "时间 / 人群 / 物件",
    "Object-led cultural learning": "物件引导的文化学习",
    "Three cultural shifts made the learning journey clearer.": "三个文化转变让学习旅程更清晰。",
    "Luxury & Status": "奢侈与身份",
    "Rare access": "稀缺接触",
    "Tea enters elite and aristocratic spaces, helping learners understand status, scarcity and early access.": "茶进入精英和贵族空间，帮助学习者理解身份、稀缺性和早期接触。",
    "Social Ritual & Identity": "社交仪式与身份",
    "Shared behaviour": "共享行为",
    "Afternoon tea becomes a social ritual connected with class, identity, imitation and public life.": "下午茶成为与阶层、身份、模仿和公共生活相关的社交仪式。",
    "Mass Access & Service Innovation": "大众可及与服务创新",
    "Scalable service": "可规模化服务",
    "Tea bags, co-op stores and standardised packaging make tea more affordable, teachable and widely accessible.": "茶包、合作社商店和标准化包装让茶变得更可负担、更可教学，也更容易被大众接触。",
    "Crazy 8s helped generate and filter possible learning formats.": "Crazy 8s 帮助生成并筛选可能的学习形式。",
    "Generated ideas including board games, short films, sound tea bags, miniature models, workshops and interactive screens.": "生成了桌游、短片、声音茶包、微缩模型、工作坊和互动屏幕等想法。",
    "Some ideas were engaging, but many were too complex, too technology-heavy or weak as teaching tools for a peer-tested classroom-style prototype.": "部分想法很吸引人，但很多过于复杂、技术负担过重，或作为课堂式同伴测试原型的教学工具不够强。",
    "The outcome needed to work in a classroom-like learning context with short attention spans and mixed learning needs.": "最终产出需要适用于类似课堂的学习语境，面对较短注意力和混合学习需求。",
    "Select stop-motion and object-based interaction because they balanced accessibility, storytelling, feasibility and engagement.": "选择定格动画与物件互动，因为它们在可及性、叙事、可行性和参与度之间取得平衡。",
    "Criterion 01": "标准 01",
    "Criterion 02": "标准 02",
    "Criterion 03": "标准 03",
    "Criterion 04": "标准 04",
    "Historical accuracy": "历史准确性",
    "Middle-school accessibility": "中学生可理解性",
    "Teaching-tool potential": "教学工具潜力",
    "Feasibility & engagement": "可行性与参与度",
    "SCAMPER turned many ideas into specific design decisions.": "SCAMPER 将多个想法转化为具体设计决策。",
    "Substitute": "替代",
    "Eliminate": "删除",
    "Adapt": "改造",
    "Rearrange": "重组",
    "Combine": "组合",
    "Use stop-motion instead of live shooting": "用定格动画替代真人拍摄",
    "Remove high-barrier VR ideas": "移除高门槛 VR 想法",
    "Treat tea bags as cultural containers": "把茶包视为文化容器",
    "Move interaction after each segment": "把互动移到每段之后",
    "Merge animation with object-based interaction": "将动画与物件互动结合",
    "From beautiful storytelling to structured learning.": "从漂亮叙事转向结构化学习。",
    "Feedback:": "反馈：",
    "Issue:": "问题：",
    "Design Change:": "设计调整：",
    "The prototype was tested through peer feedback and classroom-style review.": "原型通过同伴反馈和课堂式评审进行测试。",
    "A long linear story was less effective than short learning modules with interaction after each segment.": "长线性故事不如每段后有互动的短学习模块有效。",
    "Add a separate interactive prompt after each animation segment.": "在每个动画片段后加入独立互动提示。",
    "The tea bag appeared only at the end.": "茶包只在结尾出现。",
    "The key object felt abrupt and carried too little meaning.": "关键物件出现得突兀，承载意义不足。",
    "Transform tea bags into a dedicated learning module.": "将茶包转化为独立学习模块。",
    "Important information was implicit in the visuals.": "重要信息隐含在视觉中。",
    "Students could remember surface details but miss the deeper service message.": "学生能记住表层细节，但容易错过更深层的服务信息。",
    "Divide the story into three standalone micro-course modules.": "将故事拆分为三个独立微课程模块。",
    "Some scenes were visually attractive.": "有些场景视觉上很吸引人。",
    "They did not clearly support the learning objective.": "但它们没有清晰支持学习目标。",
    "Remove visually beautiful but pedagogically weak scenes.": "移除视觉漂亮但教学意义较弱的场景。",
    "Three micro-learning modules connect culture with service thinking.": "三个微学习模块连接文化与服务思维。",
    "Module 01 / 1680s": "模块 01 / 1680 年代",
    "Tea enters Scotland as a rare luxury": "茶作为稀缺奢侈品进入苏格兰",
    "Learning focus: status, packaging, early access and social class.": "学习重点：身份、包装、早期接触与社会阶层。",
    "Module 02 / 19th century": "模块 02 / 19 世纪",
    "Afternoon tea becomes a social ritual": "下午茶成为社交仪式",
    "Learning focus: identity, imitation, customer expectations and experience design.": "学习重点：身份、模仿、顾客期待与体验设计。",
    "Module 03 / Early 20th century": "模块 03 / 20 世纪初",
    "Tea bags and factories create mass access": "茶包与工厂创造大众可及性",
    "Learning focus: standardisation, affordability, business model and inclusive service.": "学习重点：标准化、可负担性、商业模式与包容性服务。",
    "The tea bag became a service innovation metaphor.": "茶包成为服务创新的隐喻。",
    "Handmade / premium model": "手工 / 高端模式",
    "High ritual, lower scalability": "高仪式感，较低可规模化",
    "Traditional service can feel beautiful and personal, but it may require more time, training and labour.": "传统服务可以很精致、很个人化，但通常需要更多时间、培训和劳动力。",
    "Tea bag / co-op / mass access model": "茶包 / 合作社 / 大众可及模式",
    "Standardised, teachable and accessible": "标准化、可教学、可接触",
    "Tea bag innovation is not only packaging innovation. It represents standardisation, lower cost, easier training, wider access and scalable service design.": "茶包创新不只是包装创新。它代表标准化、更低成本、更容易培训、更广泛可及，以及可规模化的服务设计。",
    "The proposal creates a bridge between cultural learning and service thinking.": "这个提案在文化学习与服务思维之间建立桥梁。",
    "Cultural connection": "文化连接",
    "Classroom discussion": "课堂讨论",
    "Inclusive service thinking": "包容性服务思维",
    "Could help learners connect familiar heritage objects with modern hospitality and service experience.": "可以帮助学习者把熟悉的遗产物件与现代 hospitality 和服务体验连接起来。",
    "Could support discussion by making abstract cultural and business concepts easier to understand.": "可以通过让抽象文化和商业概念更易理解来支持课堂讨论。",
    "Could help hospitality learners think about pricing, accessibility, customer inclusivity and scalable service design.": "可以帮助 hospitality 学习者思考定价、可及性、顾客包容性和可规模化服务设计。",
    "Cultural education needs more than beautiful storytelling.": "文化教育需要的不只是漂亮叙事。",
    "Meaning needs structure": "意义需要结构",
    "Objects can carry service logic": "物件可以承载服务逻辑",
    "Learning should transfer": "学习应该可以迁移",
    "For young learners, visual storytelling needs direct learning cues, interaction and immediate processing moments.": "对年轻学习者来说，视觉叙事需要直接学习提示、互动和即时处理信息的时刻。",
    "The tea bag helped translate abstract ideas such as standardisation, lower cost and wider access into a concrete learning object.": "茶包帮助把标准化、低成本和更广泛可及等抽象概念转译为具体学习物件。",
    "A strong educational service experience helps learners understand not only what happened in the past, but why it matters now and how it can inform future service decisions.": "强的教育服务体验不仅帮助学习者理解过去发生了什么，也帮助他们理解为什么这对当下重要，以及它如何启发未来服务决策。",
    "What This Project Demonstrates": "这个项目展示了什么",
    "Competencies for service, transformation and innovation roles": "面向服务、转型与创新岗位的能力",
    "Research filtering": "研究筛选",
    "Learning experience design": "学习体验设计",
    "Iteration through testing": "通过测试迭代",
    "Service innovation framing": "服务创新框架",
    "Turning fragmented cultural research into a teachable narrative with clear learning moments.": "将碎片化文化研究转化为有清晰学习时刻的可教学叙事。",
    "Designing visual, chunked and interactive modules for different learner needs.": "为不同学习需求设计视觉化、分段式、可互动的模块。",
    "Using feedback to pivot from passive storytelling to structured micro-learning.": "利用反馈从被动叙事转向结构化微学习。",
    "Connecting heritage objects with inclusive business models, access and scalable service design.": "将遗产物件与包容性商业模式、可及性和可规模化服务设计连接起来。",

    "Multi-Species / Biodiversity Clock": "多物种 / 生物多样性时钟",
    "Scone Through Time": "司康时光",
    "Ear Shield": "Ear Shield 鲸声护盾",
    "SeedWalkers": "SeedWalkers 种子行者",
    "Cross-Culture Icebreaker": "跨文化破冰包",
    "Machine Mapping": "Machine Mapping 机器映射",
    "Public Creative Technology Practice": "公开创意技术实践"
  };

  // Keep complete project copy alongside the shared navigation vocabulary.
  Object.assign(zh, {
    "Home / Work / Multi-Species Biodiversity Clock": "首页 / 项目 / 多物种生物多样性时钟",
    "What if the museum ran on ecological time, not human time?": "如果博物馆跟随生态节律运行，会发生什么？",
    "The Burrell Collection": "巴勒尔珍藏馆（The Burrell Collection）",
    "Pollok Country Park": "波洛克乡村公园（Pollok Country Park）",
    "A museum experience reframed through ecological time.": "以生态时间重新组织博物馆体验。",
    "01 Museum + Park Context": "01 博物馆与公园背景",
    "02 Research Evidence": "02 调研依据",
    "03 Key Insights": "03 核心洞察",
    "04 Final Biodiversity Clock": "04 生物多样性时钟方案",
    "05 Potential Impact Timeline": "05 预期影响时间线",
    "Overview": "项目概览",
    "Context": "项目背景",
    "Research": "调研",
    "Development": "设计推演",
    "Impact": "项目价值",
    "Reflection": "复盘与思考",
    "A museum inside a living park system.": "一座身处鲜活生态系统中的博物馆。",
    "Real-site grounding": "真实场地背景",
    "Pollok Park + Burrell Collection": "波洛克公园与巴勒尔珍藏馆",
    "This project began from a real place: Pollok Country Park and The Burrell Collection. Through field observation and stakeholder-informed research, the team explored how the museum and park could help visitors notice ecological rhythms that are usually invisible in a human-centred visitor experience.": "项目以波洛克乡村公园与巴勒尔珍藏馆为真实场地。团队通过实地观察及相关方调研，探索如何将博物馆与公园连接起来，让访客感知以人为中心的游览体验中容易被忽视的生态节律。",
    "Human institution logic": "机构的运行逻辑",
    "Museum time": "博物馆时间",
    "Opening hours, exhibitions, visitor comfort and cultural display shape how people encounter the site.": "开放时间、展览安排、游览舒适度与文化展示，共同塑造人们使用场地的方式。",
    "Ecological logic": "生态的运行逻辑",
    "Species time": "物种时间",
    "Seasonal rhythms, feeding patterns, migration, habitats and disturbance sensitivity shape how non-human species live in the same place.": "季节变化、觅食规律、迁徙、栖息地与对干扰的敏感程度，决定其他物种如何在同一场地中生活。",
    "The design problem was not only lack of information.": "设计问题不仅在于信息不足。",
    "Visitors could pass through Pollok Country Park without sensing the timing, needs and vulnerabilities of the species around them. The challenge was to move beyond biodiversity as static content and design an experience that makes ecological relationships feel immediate, situated and actionable.": "访客可能穿行于公园，却不了解周围物种的活动时间、需求及脆弱性。设计挑战是让生物多样性从静态知识变成与当下场景相关、可感知且能引导行动的体验。",
    "The project therefore asked how The Burrell Collection could act less like a separate cultural container and more like a public interface for the living park around it.": "因此，项目探索巴勒尔珍藏馆如何超越独立文化展馆的角色，成为公众理解周边公园生态的入口。",
    "My Role": "我的职责",
    "Research, sense-making, prototype development and visual communication.": "调研、洞察提炼、原型开发与视觉沟通。",
    "Research synthesis": "调研整合",
    "I helped collect case studies, organise field and desk research, analyse stakeholders and translate ecological evidence into design opportunities.": "参与案例收集、实地与案头调研整理、利益相关者分析，并将生态信息转化为设计机会。",
    "Concept logic": "概念构建",
    "I contributed to the shift from a broad app idea toward a time-based museum-and-park experience centred on non-human rhythms.": "参与推动方案从宽泛的应用程序构想，转向以非人类物种节律为核心、连接博物馆与公园的时间体验。",
    "Visual prototyping": "视觉原型",
    "I supported the final communication by developing visual material and a tangible presentation model to make the concept easier to discuss.": "制作视觉材料与实体展示模型，支持最终方案沟通，让概念更易于理解和讨论。",
    "Research Evidence": "调研依据",
    "The research moved from broad biodiversity concern to situated multi-species interaction.": "从宏观生物多样性议题，聚焦到具体场地中的多物种互动。",
    "01 / Animal-Aided Design": "01 / 动物辅助设计",
    "Start from species needs.": "从物种需求出发。",
    "AAD reframed the site from a human leisure space into a shared habitat where animal life cycles, food, shelter and movement patterns become design inputs.": "动物辅助设计（AAD）将场地视为共享栖息地，把动物生命周期、食物、庇护与活动路径纳入设计依据。",
    "02 / Field research": "02 / 实地调研",
    "Species are unevenly distributed.": "物种分布并不均匀。",
    "Observation suggested that ecological life was concentrated in specific zones such as North Wood, rather than evenly spread across the park.": "实地观察发现，生态活动集中于北部林地等特定区域，并非均匀分布在整个公园。",
    "03 / Management insight": "03 / 管理视角",
    "Intervention needs better ecological knowledge.": "场地干预需要更充分的生态认知。",
    "Park management choices can affect species, but the public often cannot see why certain habitats, paths or seasonal protections matter.": "公园管理决策会影响物种，但公众往往不了解特定栖息地、路径安排或季节性保护措施的重要性。",
    "04 / Stakeholder input": "04 / 相关方交流",
    "Emotional narratives beat abstract data.": "有情感连接的叙事更容易引发共鸣。",
    "Stakeholder conversations with people connected to the park's biodiversity and visitor experience highlighted that emotional narratives, species presence and visitor motivation were more effective than abstract biodiversity facts alone.": "与公园生物多样性及访客体验相关人员的交流表明，情感叙事、具体物种与访客动机，比单独呈现抽象的生物多样性知识更能促进参与。",
    "AAD and precedent research source material": "动物辅助设计与参考案例研究材料",
    "Field research findings translated into design evidence": "从实地调研发现提炼设计依据",
    "Stakeholder quotes and engagement insights": "相关方访谈摘录与参与洞察",
    "Key Insights": "核心洞察",
    "The project became about changing how visitors sense the park.": "改变访客感知公园的方式。",
    "Insight 01": "洞察 01",
    "Interaction matters more than species count. People need to understand relationships, not just identify animals.": "互动比物种数量更重要。人们需要理解生态关系，而不只是辨认动物。",
    "Insight 02": "洞察 02",
    "Participation is fragmented. Park users and museum visitors often belong to overlapping but disconnected publics.": "参与体验较为分散。公园使用者与博物馆访客有所重叠，但两者的活动往往缺少连接。",
    "Insight 03": "洞察 03",
    "Ecological processes work on longer timescales than visitor attention, so the experience needed to make seasonal and historical rhythms legible.": "生态变化的时间尺度远长于访客停留时间，因此需要让季节与历史节律变得可读、可理解。",
    "How might we": "设计命题",
    "encourage visitors to experience the park from a non-human perspective, shifting passive observation into active ecological participation?": "如何鼓励访客从其他物种的视角体验公园，将被动观看转化为主动的生态参与？",
    "Design Development": "设计推演",
    "From information display to a phygital biodiversity clock.": "从信息展示走向实体与数字结合的生物多样性时钟。",
    "Prototype 01": "原型 01",
    "Exhibition": "展览展示",
    "An early public display approach that made biodiversity visible but still felt like information delivery.": "早期通过公共展示呈现生物多样性，但体验仍偏向单向信息传递。",
    "Concept": "概念方案",
    "Ecological signboard": "生态导览牌",
    "A site-based direction that began connecting species presence with visitor movement and park context.": "结合具体场地，将物种分布、访客移动与公园环境联系起来。",
    "Prototype 02": "原型 02",
    "Clock + map + app": "时钟 + 地图 + 应用",
    "A digital system explored time, mapping and visitor action, but still needed a stronger tangible experience.": "数字系统探索了时间、地图与访客行动的连接，但仍需要更鲜明的实体体验。",
    "Final": "最终方案",
    "Clock + receipt": "时钟 + 互动票据",
    "The final direction combined a public clock, rotating structure, ecological time display and collectible receipt.": "最终方案整合公共时钟、旋转结构、生态时间展示与可收藏的互动票据。",
    "Design iteration from exhibition and signboard ideas toward a phygital clock and receipt system.": "从展览与导览牌，逐步迭代为实体与数字结合的时钟及票据系统。",
    "Final Outcome": "最终成果",
    "A clock that translates museum visiting into ecological timing.": "用一座时钟，将博物馆游览连接到生态节律。",
    "01 / Biodiversity Clock": "01 / 生物多样性时钟",
    "Current time, animal rhythms and park activity": "当前时间、动物节律与公园活动",
    "The public interface shows current ecological activity, five key animal rhythms, status cues and suggested time windows across the park day.": "公共界面展示当前生态活动、五种重点动物的节律、状态提示及一天中适宜观察的时间段。",
    "02 / Seasonal + historical time": "02 / 季节与历史时间",
    "Different scales of ecological memory": "不同时间尺度的生态记忆",
    "The system connects daily activity with plant families, habitats, animal relationships and the longer history of Pollok Country Park.": "系统将日常活动与植物科属、栖息地、动物关系及波洛克公园的长期历史相连接。",
    "03 / Interactive Receipt": "03 / 互动票据",
    "A tangible takeaway from the park-museum encounter": "一份可以带走的公园与博物馆体验",
    "Each receipt links a species in the park with a museum collection object and a reflective question, extending the experience beyond the screen.": "每张票据将公园中的一种物种、博物馆中的一件藏品与一个启发思考的问题关联起来，让体验延伸至屏幕之外。",
    "User Journey": "用户旅程",
    "Visitors move from noticing to collecting, reflecting and changing behaviour.": "从注意、收集与思考，走向行为改变。",
    "Encounter": "发现",
    "A visitor enters the museum-park threshold and sees ecological time instead of only human opening hours.": "访客来到博物馆与公园的交汇处，看到的不仅是开放时间，还有生态活动时间。",
    "Interpret": "理解",
    "The clock translates species activity into cues about who is active, where they may be, and what human behaviours matter.": "时钟提示哪些物种正在活动、可能出现在哪里，以及人的哪些行为会影响它们。",
    "Collect": "收集",
    "The interactive receipt gives the visitor a physical prompt that connects park species with cultural collection objects.": "互动票据作为实体提示，将公园物种与文化藏品连接起来。",
    "Act": "行动",
    "The visitor is invited to leave with a different sense of timing, movement and responsibility inside the shared ecological site.": "鼓励访客以新的时间意识、移动方式与责任感，参与共享生态场地中的活动。",
    "Storyboard source visual for the visitor journey.": "访客旅程故事板原始视觉材料。",
    "Watch project storyboard video": "观看项目故事板视频",
    "Potential Impact Timeline": "预期影响时间线",
    "The proposal imagines the museum gradually becoming an ecological learning and sensing hub.": "方案展望博物馆逐步成为生态学习与感知的公共节点。",
    "See": "看见",
    "Visitors begin noticing disturbance, species presence and the weak connection between museum and park experience.": "访客开始注意到环境干扰、物种存在，以及博物馆与公园体验之间尚未充分建立的连接。",
    "Understand": "理解",
    "Eco-routing, sensor input and habitat buffer zones support clearer links between behaviour and biodiversity.": "生态路线、传感信息与栖息地缓冲区，帮助公众理解行为与生物多样性之间的联系。",
    "Ecological cues and guidance could reduce avoidable disturbance and help visitors build more careful habits around shared habitats.": "生态提示与引导有望减少可避免的干扰，帮助访客在共享栖息地中形成更谨慎的行动习惯。",
    "Low-impact visiting habits become more normal as human behaviour aligns more closely with species rhythms.": "随着人的行为更贴近物种节律，低干扰游览有望逐渐成为常态。",
    "Co-exist": "共存",
    "The site could move toward more balanced coexistence, where visitor behaviour is shaped by seasonal ecological rhythms and lighter-touch intervention.": "通过季节性生态节律与适度干预引导访客行为，场地有望走向更平衡的共存。",
    "Designing for species does not mean designing humans out.": "为其他物种设计，也要考虑人的合理参与。",
    "Physical over default screen logic": "以实体体验补充屏幕交互",
    "The project moved away from a purely app-based system because ecological participation needed a more tangible, situated and collectible form.": "方案不再局限于应用程序，因为生态参与需要更有触感、与场地关联且可留存的体验形式。",
    "Protection versus coexistence": "保护与共存的平衡",
    "The project keeps a productive tension open: biodiversity may benefit from reduced human presence, but design can make necessary human presence more aware and less harmful.": "减少人类活动可能有利于生物多样性；与此同时，设计也能让必要的公共活动更加自觉、减少伤害。",
    "From data to behaviour": "从数据走向行为",
    "The strongest opportunity was not simply displaying species data, but helping people feel how their timing, route and attention affect a shared ecological system.": "关键机会在于让人们感知自己的活动时间、路线与注意力如何影响共享生态系统，而不只是展示物种数据。",
    "Competencies for service and transformation design roles": "服务与转型设计能力",
    "Systems thinking": "系统思维",
    "Reframing a museum and park as one socio-ecological service system with human and non-human stakeholders.": "将博物馆与公园视为同一社会生态服务系统，同时考虑人类与非人类相关方。",
    "Research translation": "调研转化",
    "Turning desk research, field observation and stakeholder insight into experience principles and design decisions.": "将案头研究、实地观察及相关方洞察转化为体验原则与设计决策。",
    "Future prototyping": "未来体验原型",
    "Using speculative but grounded objects, receipts, journeys and timelines to communicate a possible public service.": "通过有现实依据的概念物件、票据、旅程与时间线，呈现未来公共服务的可能性。",
    "Critical technology framing": "审慎的技术定位",
    "Keeping AI and sensing as careful support tools rather than presenting technology as a simple solution to ecological complexity.": "将 AI 与感知技术作为辅助工具，审慎回应生态系统的复杂性。",
    "Back to Work": "返回项目列表",
    "Next: Ear Shield": "下一项目：鲸声护盾",
    "Previous: Ear Shield": "上一项目：鲸声护盾",
    "Next: SeedWalkers": "下一项目：种子行者",
    "Previous: SeedWalkers": "上一项目：种子行者",
    "Next: Machine Mapping": "下一项目：机器映射",
    "Previous: Machine Mapping": "上一项目：机器映射",
    "Next: Cross-Culture": "下一项目：跨文化破冰包",
    "Previous: Biodiversity Clock": "上一项目：生物多样性时钟",
    "Type": "项目类型",
    "Duration": "项目周期",
    "In this project": "在本项目中",
    "System": "系统架构",
    "Prototype": "原型",
    "Page-by-page evidence": "设计过程与成果详解",
    "Your browser does not support embedded video. Use the product link below to view the published project.": "你的浏览器暂不支持内嵌视频，请通过下方产品链接查看已发布的项目。",
    "Language switcher": "切换语言"
  });

  Object.assign(zh, {
    "Home / Work / Ear Shield": "首页 / 项目 / 鲸声护盾",
    "01 / Environmental technology": "01 / 环境技术",
    "A speculative acoustic monitoring device and public installation exploring how human underwater noise disrupts toothed whale perception.": "通过概念性声学监测设备与公共互动装置，探索人类水下噪声如何干扰齿鲸的感知。",
    "Making underwater acoustic disruption visible.": "让水下声学干扰变得可见。",
    "Toothed whales rely on echolocation for orientation, hunting and communication. Human-made underwater noise can interfere with this sensory system and increase stranding risk.": "齿鲸依赖回声定位进行定向、捕猎与交流。人类产生的水下噪声可能干扰这一感知系统，并增加搁浅风险。",
    "The issue is invisible to most audiences. The project needed to translate underwater acoustic disruption into a tangible device concept and public-facing experience.": "多数观众无法直接感知这一问题。项目将水下声学干扰转化为可理解的设备概念与面向公众的互动体验。",
    "I moved from whale and sound-wave research into bionic suction ideation, Python acoustic analysis, device system design, and an Arduino / TouchDesigner installation.": "从鲸类与声波研究出发，开展仿生吸附构想、Python 声学分析、设备系统设计，以及 Arduino 与 TouchDesigner 互动装置开发。",
    "The outcome is a speculative whale monitoring system and exhibition prototype that helps audiences understand how human noise affects whale perception.": "成果包括概念性鲸类监测系统与展览互动原型，帮助公众理解人类噪声对鲸类感知的影响。",
    "Complete Ear Shield project archive": "鲸声护盾：完整项目档案",
    "Each image is shown because it proves a specific design decision, research step or prototype development moment.": "每张作品板均对应具体的设计决策、调研步骤或原型开发阶段；下方中文说明提炼关键问题与设计回应。",
    "Page 01 - Project overview": "第 01 页 · 项目概览",
    "Problem: The topic needed a clear entry point.": "问题：议题需要清晰的切入点。",
    "My response: I framed it as a smart whale monitoring and echo-enhancement system connecting conservation, acoustic sensing and public communication.": "设计回应：提出连接生态保护、声学感知与公共沟通的智能鲸类监测及回声增强系统概念。",
    "Page 02 - Background research": "第 02 页 · 背景研究",
    "Problem: Whale strandings are hard to connect to invisible underwater noise.": "问题：公众难以将鲸类搁浅与不可见的水下噪声联系起来。",
    "My response: I mapped human noise, sonar interference and sperm whale echolocation to establish noise as sensory disruption.": "设计回应：梳理人类噪声、声呐干扰与抹香鲸回声定位之间的关系，将噪声界定为感知干扰。",
    "Page 03 - Species and sound research": "第 03 页 · 物种与声音研究",
    "Problem: A generic whale story would be too broad.": "问题：泛泛讨论鲸类会使研究范围过大。",
    "My response: I narrowed the project to toothed whales and sperm whales, then studied echo characteristics and sound-wave feedback.": "设计回应：聚焦齿鲸及抹香鲸，研究回声特征与声波反馈。",
    "Page 04 - Concept ideation and acoustic analysis": "第 04 页 · 概念推演与声学分析",
    "Problem: The device needed a plausible attachment and monitoring logic.": "问题：设备需要合理的附着方式与监测逻辑。",
    "My response: I explored octopus-inspired suction and tested Python audio analysis using MFCC, Chroma and Mel spectrogram comparisons.": "设计回应：探索章鱼启发的吸附结构，并通过 Python 比较 MFCC、Chroma 与 Mel 频谱，开展音频分析测试。",
    "Page 05 - Device system design": "第 05 页 · 设备系统设计",
    "Problem: The concept needed to become a system, not a single object sketch.": "问题：概念需要发展为完整系统。",
    "My response: I defined device components, health monitoring, depth adaptation, noise reduction and whale database logic.": "设计回应：定义设备组件、健康监测、深度适应、降噪与鲸类数据库的系统逻辑。",
    "Page 06 - Interactive prototype": "第 06 页 · 互动原型",
    "Problem: Audiences cannot directly feel underwater acoustic interference.": "问题：观众无法直接感受水下声学干扰。",
    "My response: I used Arduino, ultrasonic sensing, gesture input, TouchDesigner and Blender particle visuals to simulate disrupted whale perception.": "设计回应：结合 Arduino、超声波感应、手势输入、TouchDesigner 与 Blender 粒子视觉，模拟鲸类感知受到干扰的体验。",
    "Page 07 - Exhibition and stakeholder plan": "第 07 页 · 展览与相关方规划",
    "Problem: The work needed evidence of public communication and future collaboration potential.": "问题：项目需要展示公共沟通效果与后续合作可能性。",
    "My response: I documented exhibition interaction and mapped stakeholders including research institutes, government, education bodies and environmental organizations.": "设计回应：记录展览现场互动，并梳理研究机构、政府、教育机构与环保组织等潜在相关方。",
    "What Ear Shield demonstrates": "鲸声护盾展示的能力",
    "Ecological framing": "生态议题定义",
    "Turning underwater noise and whale perception into a clear environmental design problem.": "将水下噪声与鲸类感知转化为明确的环境设计问题。",
    "Speculative system logic": "概念系统构建",
    "Connecting monitoring device behaviour, acoustic analysis and stakeholder planning into one concept.": "将监测设备行为、声学分析与相关方规划整合为统一概念。",
    "Physical computing": "实体交互开发",
    "Using Arduino, TouchDesigner and Blender to create an interaction that communicates invisible acoustic disruption.": "使用 Arduino、TouchDesigner 与 Blender 构建互动，将不可见的声学干扰转化为可感知体验。",
    "Making a complex conservation issue easier for exhibition audiences to understand and discuss.": "帮助展览观众理解并讨论复杂的生态保护议题。",
    "Home / Work / SeedWalkers": "首页 / 项目 / 种子行者",
    "02 / Service design + AR": "02 / 服务设计与增强现实",
    "An AR service system using seed cards, public participation and ecological data to reconnect fragmented urban biodiversity.": "结合种子卡、公众参与与生态数据，通过增强现实服务系统探索城市生物多样性的重新连接。",
    "A city-scale biodiversity service concept.": "面向城市生物多样性的服务概念。",
    "Urban greenery can look sufficient while still being ecologically weak because of monoculture and fragmentation.": "城市绿化看似充足，却可能因物种单一与空间碎片化而缺乏生态韧性。",
    "The project needed to connect city-scale carbon and biodiversity issues with everyday public participation.": "项目需要将城市尺度的碳排放与生物多样性议题，连接到公众日常参与。",
    "I used carbon research, biodiversity logic, ENVI/ArcGIS analysis, service blueprinting and AR prototyping to shape the service.": "结合碳排放研究、生物多样性分析、ENVI / ArcGIS 空间分析、服务蓝图与 AR 原型，构建服务方案。",
    "The outcome is a seed-card and AR planting service that turns ecological restoration into a participatory journey.": "提出种子卡与 AR 种植服务，将生态修复转化为公众可以参与的体验旅程。",
    "Complete SeedWalkers project archive": "种子行者：完整项目档案",
    "These pages show the research, service logic, stakeholder system and technical prototype behind the project.": "以下作品板展示研究、服务逻辑、相关方系统与技术原型；每页配有中文问题与设计回应。",
    "Page 08 - Project overview": "第 08 页 · 项目概览",
    "Problem: Climate pressure, biodiversity loss and public participation needed one clear proposition.": "问题：气候压力、生物多样性流失与公众参与需要统一的设计命题。",
    "My response: I framed SeedWalkers as an AR service using seed cards and participatory planting to reconnect fragmented ecosystems.": "设计回应：以种子卡与参与式种植构建 AR 服务，探索重新连接碎片化生态系统。",
    "Page 09 - Carbon and city background": "第 09 页 · 城市碳排放背景",
    "Problem: Green coverage alone does not prove ecological resilience.": "问题：绿化覆盖率不能单独证明生态韧性。",
    "My response: I used Changsha carbon and vegetation data to show the gap between emissions and absorption.": "设计回应：利用长沙碳排放与植被数据，呈现排放与吸收之间的差距。",
    "Page 10 - Biodiversity logic": "第 10 页 · 生物多样性逻辑",
    "Problem: Planting more greenery alone does not guarantee ecosystem health.": "问题：单纯增加绿植不一定能改善生态系统健康。",
    "My response: I mapped how tree diversity supports habitats, birds, seed dispersal and urban carbon cycling.": "设计回应：梳理树种多样性对栖息地、鸟类、种子传播与城市碳循环的支持关系。",
    "Page 11 - Urban vegetation analysis": "第 11 页 · 城市植被分析",
    "Problem: The city problem was fragmentation and monoculture, not just a lack of green space.": "问题：城市生态挑战还包括植被碎片化与物种单一。",
    "My response: I analyzed plant diversity and target ratios of trees, shrubs and ground cover.": "设计回应：分析植物多样性，以及乔木、灌木与地被的目标配比。",
    "Page 12 - Service framework and app structure": "第 12 页 · 服务框架与应用架构",
    "Problem: Ecological strategy needed to become a user-facing service.": "问题：生态策略需要转化为面向用户的服务。",
    "My response: I designed seed collection, AR planting, city progress, ranking, maps, feedback and low-fidelity app screens.": "设计回应：设计种子领取、AR 种植、城市进度、排行、地图与反馈模块，并制作应用低保真界面。",
    "Page 13 - User journey": "第 13 页 · 用户旅程",
    "Problem: Users needed a simple reason to participate and understand contribution.": "问题：用户需要明确的参与动机，并能理解自己的贡献。",
    "My response: I created a journey from QR login and seed cards to AR planting, badges and sharing.": "设计回应：构建从扫码登录、领取种子卡，到 AR 种植、获得徽章与分享的完整旅程。",
    "Page 14 - Stakeholder map and service blueprint": "第 14 页 · 相关方地图与服务蓝图",
    "Problem: City-scale ecological services cannot rely only on individual users.": "问题：城市级生态服务需要多方协作。",
    "My response: I mapped users, technical staff, manufacturers, garden designers, government and maintenance teams.": "设计回应：梳理用户、技术人员、制造商、园林设计师、政府与维护团队的协作关系。",
    "Page 15 - Technical implementation": "第 15 页 · 技术实现",
    "Problem: The service needed credible spatial and technical grounding.": "问题：服务方案需要可靠的空间分析与技术支撑。",
    "My response: I used ENVI, ArcGIS/NDVI, Blender and Unity to support vegetation analysis and AR prototyping.": "设计回应：使用 ENVI、ArcGIS / NDVI、Blender 与 Unity，支持植被分析和 AR 原型制作。",
    "What SeedWalkers demonstrates": "种子行者展示的能力",
    "Service design": "服务设计",
    "Connecting ecological research, public participation and backstage support into a coherent service concept.": "将生态研究、公众参与与后台支持整合为连贯的服务概念。",
    "Environmental research": "环境研究",
    "Using carbon, biodiversity and vegetation analysis to define why the service matters.": "通过碳排放、生物多样性与植被分析，明确服务的必要性。",
    "Spatial analysis": "空间分析",
    "Using ENVI and ArcGIS/NDVI evidence to ground the service in urban vegetation conditions.": "利用 ENVI 与 ArcGIS / NDVI 分析，使服务设计建立在城市植被条件之上。",
    "AR prototyping": "增强现实原型",
    "Turning seed-card participation into a digital planting flow that people could imagine using in the city.": "将种子卡参与机制转化为可理解的数字种植流程，呈现其在城市中的使用方式。",
    "Home / Work / Machine Mapping": "首页 / 项目 / 机器映射",
    "03 / AI + critical interaction": "03 / AI 与批判性交互",
    "A reflective experiment using speech recognition, image search and 3D visualization to question how color stereotypes are formed and repeated.": "结合语音识别、图像检索与三维可视化的反思性实验，探讨色彩刻板印象如何形成并被重复。",
    "A critical interaction experiment about social input and machine memory.": "关于社会输入与机器记忆的批判性交互实验。",
    "Color meanings are shaped by culture, markets, social agreement and personal experience.": "色彩含义受到文化、市场、社会共识与个人经验的共同塑造。",
    "The project needed to make machine learning and social cognition visible without forcing a single conclusion.": "项目希望让机器学习与社会认知的关系变得可见，同时保留开放的讨论空间。",
    "Participants discussed colors, the system extracted keywords, searched images, processed color blocks and visualized machine memory in Blender.": "参与者讨论色彩，系统提取关键词、检索图像并处理色块，最终在 Blender 中可视化呈现机器记忆。",
    "The outcome is a reflective prototype that reveals how social input can shape machine memory.": "形成可运行的反思性交互原型，呈现社会输入如何塑造机器记忆。",
    "Complete Machine Mapping project archive": "机器映射：完整项目档案",
    "These pages show the cultural research, interaction logic and technical system.": "以下作品板呈现文化研究、交互逻辑与技术系统，并配有逐页中文解读。",
    "Page 16 - Project overview": "第 16 页 · 项目概览",
    "Problem: Machine learning bias and social cognition are abstract.": "问题：机器学习偏差与社会认知较为抽象。",
    "My response: I framed the project as a reflective experiment where participants influence machine memory through discussion.": "设计回应：将项目构建为参与者通过讨论影响机器记忆的反思性实验。",
    "Page 17 - Color stereotype research": "第 17 页 · 色彩刻板印象研究",
    "Problem: Color meanings feel natural although they are socially constructed.": "问题：色彩含义看似天然，实际受到社会建构影响。",
    "My response: I researched cultural, historical, market and social construction of color symbolism.": "设计回应：研究色彩象征的文化、历史、市场与社会建构背景。",
    "Page 18 - Machine-learning metaphor": "第 18 页 · 机器学习隐喻",
    "Problem: A normal interface would hide the learning process.": "问题：常规界面难以呈现学习过程。",
    "My response: I designed a loop where discussion becomes keywords, keywords become images and images become visual memory.": "设计回应：建立讨论转化为关键词、关键词转化为图像、图像转化为视觉记忆的循环。",
    "Page 19 - Design development": "第 19 页 · 设计开发",
    "Problem: Conversation needed to become visible machine feedback.": "问题：对话需要转化为可见的机器反馈。",
    "My response: I built a pipeline with audio input, Arduino, Python keyword extraction, image search, color processing and Blender visualization.": "设计回应：搭建包含音频输入、Arduino、Python 关键词提取、图像检索、色彩处理与 Blender 可视化的流程。",
    "Page 20 - Participant interaction flow": "第 20 页 · 参与者交互流程",
    "Problem: Participants needed structure without being told what to think.": "问题：参与者需要讨论结构，同时保有自主思考空间。",
    "My response: I used staged discussions around blue, green and pink, then let the machine generate feedback.": "设计回应：围绕蓝色、绿色与粉色开展分阶段讨论，再由机器生成反馈。",
    "Page 21 - Technical implementation": "第 21 页 · 技术实现",
    "Problem: The critical concept needed a working technical system.": "问题：批判性概念需要可运行的技术系统支撑。",
    "My response: I used Arduino sensing, Python, Vosk, image matching and Blender shader/space visualization.": "设计回应：结合 Arduino 感应、Python、Vosk 语音识别、图像匹配与 Blender 着色器及空间可视化。",
    "What Machine Mapping demonstrates": "机器映射展示的能力",
    "Critical AI thinking": "AI 批判性思考",
    "Questioning how human language, cultural assumptions and machine processes shape each other.": "探讨人类语言、文化预设与机器处理过程如何相互塑造。",
    "Participatory interaction": "参与式交互",
    "Designing staged discussion so participants influence the system without being pushed toward one answer.": "通过分阶段讨论，让参与者影响系统，同时避免预设单一答案。",
    "Technical experimentation": "技术实验",
    "Connecting speech recognition, keyword extraction, image search and Blender visualization into one prototype logic.": "将语音识别、关键词提取、图像检索与 Blender 可视化整合为完整原型。",
    "Data visualisation": "数据可视化",
    "Making invisible social input visible as a changing machine memory environment.": "将不可见的社会输入呈现为不断变化的机器记忆空间。"
  });

  Object.assign(zh, {
    "Home / Work / Cross-Culture Icebreaker": "首页 / 项目 / 跨文化破冰包",
    "04 / Social design": "04 / 社会设计",
    "A social pack and board-game experience helping Chinese international students exchange cultural backgrounds and build early connections.": "通过社交包与桌游体验，帮助中国留学生交流文化背景、建立初步联系。",
    "Service design / social design / game experience": "服务设计 / 社会设计 / 游戏体验",
    "Group project contribution across research, system framing and prototype communication": "在团队项目中参与调研、系统构建与原型沟通",
    "Survey, personas, 5W1H, service system map, prototype": "问卷调研、用户画像、5W1H 分析、服务系统图与原型",
    "Social package and board-game kit": "社交包与桌游套件",
    "A social design proposal for low-pressure cultural exchange.": "面向低压力文化交流的社会设计方案。",
    "Chinese international students may face social anxiety, language barriers and limited low-pressure opportunities to connect.": "中国留学生可能面临社交焦虑、语言障碍，以及缺少低压力交流机会等问题。",
    "The project needed to break the ice naturally without forcing uncomfortable direct interaction.": "项目需要创造自然的破冰机会，避免让参与者被迫进入不自在的直接交流。",
    "The team used survey data, personas, service mapping, social-pack flows and game mechanics.": "团队结合问卷数据、用户画像、服务地图、社交包流转与游戏机制开展设计。",
    "The outcome is a two-part social system: a rotating social pack and a collaborative board-game kit.": "成果由两部分组成：轮流传递的社交包与协作式桌游套件。",
    "Complete Cross-Culture Icebreaker project archive": "跨文化破冰包：完整项目档案",
    "These pages show the user research, system logic, prototype and final demonstration.": "以下作品板展示用户研究、系统逻辑、原型与最终演示，并配有逐页中文解读。",
    "Page 22 - Project overview": "第 22 页 · 项目概览",
    "Problem: Students may want connection but struggle to start interaction naturally.": "问题：学生希望建立联系，却难以自然开启交流。",
    "My response: The group proposed a social kit and game-based experience for structured cross-cultural exchange.": "设计回应：团队提出社交套件与游戏体验，为跨文化交流提供结构化支持。",
    "Page 23 - Social background research": "第 23 页 · 社会背景研究",
    "Problem: The challenge needed evidence beyond assumptions about shyness.": "问题：不能仅凭害羞等假设定义社交障碍。",
    "My response: We mapped student scale, social anxiety, cultural conflict, loneliness, language barriers and adaptation issues.": "设计回应：梳理留学生群体规模、社交焦虑、文化冲突、孤独感、语言障碍与适应问题。",
    "Page 24 - User research and framing": "第 24 页 · 用户研究与问题定义",
    "Problem: Students' social barriers vary.": "问题：不同学生的社交障碍并不相同。",
    "My response: We used interviews, a 117-person questionnaire, personas, HMW and 5W1H framing.": "设计回应：结合访谈、117 人问卷、用户画像、HMW 设计提问与 5W1H 分析定义问题。",
    "Page 25 - Concept and service system": "第 25 页 · 概念与服务系统",
    "Problem: Direct face-to-face interaction can be high pressure.": "问题：直接面对面交流可能带来较大压力。",
    "My response: We explored indirect exchange through shared objects, Polaroids, journals, games and stakeholder support.": "设计回应：通过共享物件、拍立得照片、日记、游戏及相关方支持，探索间接交流方式。",
    "Page 26 - Social pack and game user flows": "第 26 页 · 社交包与游戏流程",
    "Problem: The service needed concrete interaction mechanics.": "问题：服务方案需要具体可执行的互动机制。",
    "My response: We designed a rotating social pack journey and nine-person board game with puzzle zones and cultural prompts.": "设计回应：设计社交包轮转旅程，以及结合拼图区与文化提示的九人桌游。",
    "Page 27 - Final prototype and significance": "第 27 页 · 最终原型与项目价值",
    "Problem: The proposal needed to show feasibility.": "问题：方案需要呈现可行性依据。",
    "My response: We produced physical prototypes, demo process, business canvas and participant feedback quotes.": "设计回应：制作实体原型、演示流程与商业模式画布，并整理参与者反馈。",
    "What Cross-Culture Icebreaker demonstrates": "跨文化破冰包展示的能力",
    "User research": "用户研究",
    "Using interviews, questionnaire data and personas to define barriers to early social connection.": "通过访谈、问卷数据与用户画像，识别初期社交联系中的障碍。",
    "Social design": "社会设计",
    "Creating low-pressure interaction formats that help students exchange culture without forced self-presentation.": "创造低压力互动形式，让学生无需强制自我介绍也能交流文化。",
    "Service mapping": "服务系统梳理",
    "Connecting students, organisers, schools, communities and sponsors around a repeatable social experience.": "围绕可重复开展的社交体验，连接学生、组织者、学校、社区与赞助方。",
    "Game mechanics": "游戏机制设计",
    "Using physical prompts, routes, puzzle zones and cultural questions to structure meaningful interaction.": "通过实体提示、路线、拼图区与文化问题，组织有意义的交流。",
    "Scottish afternoon tea and familiar food objects offered a clear entry point into wider questions of heritage, hospitality and service. The project explored how cultural material could become a learning experience rather than a static display.": "以苏格兰下午茶与熟悉的食物为切入点，探讨文化遗产、待客之道与服务。项目探索如何将文化材料转化为可参与的学习体验。",
    "The aim was to help students connect past social rituals with present-day service thinking, business innovation and inclusive customer experience.": "目标是帮助学习者将历史中的社交仪式，与当代服务思维、商业创新及包容性顾客体验联系起来。",
    "Early research was rich but scattered, mixing tourism stories, hotel narratives, lifestyle media, commercial references and historical sources. This made it hard to separate teachable cultural material from promotional storytelling.": "早期资料丰富但分散，混合了旅游故事、酒店叙事、生活方式媒体、商业参考与历史文献，难以区分适合教学的文化内容与宣传性叙事。",
    "The project needed to turn fragmented research into a visual, low-barrier and transferable learning experience for young learners.": "项目需要将碎片化研究转化为面向年轻学习者、视觉化、易理解且可迁移的学习体验。",
    "Rather than inventing a fictional history activity, the team used real learner needs, educational constraints and peer testing feedback to shape the project into a structured micro-learning experience.": "团队结合真实学习需求、教学条件与同伴测试反馈，将项目组织为结构化的微学习体验。",
    "Stakeholders": "利益相关者",
    "The stakeholder source was translated into three learning-needs cards for the web case study.": "将相关方研究提炼为三张学习需求卡片，便于在线阅读。",
    "Research Challenge": "研究挑战",
    "Narrowing The Scope": "聚焦研究范围",
    "This filtering step shifted the project from a broad cultural topic into a more teachable journey built around familiar objects such as scones, tea caddies and tea bags.": "经过筛选，项目从宽泛文化议题聚焦为围绕司康、茶叶罐与茶包等熟悉物件展开的学习旅程。",
    "Core Narrative": "核心叙事",
    "The dense timeline was used as source material, then rebuilt as three cultural shifts.": "以详细时间线为研究依据，重新组织为三个关键文化转变。",
    "Ideation": "创意探索",
    "Refinement": "方案优化",
    "More feasible, visual and suitable for young learners.": "更易实施、视觉化，适合年轻学习者。",
    "Lower cost and easier to deliver in a short learning session.": "成本更低，便于在短时学习活动中开展。",
    "The tea bag became a physical learning object, not only a prop.": "茶包成为承载知识的实体学习媒介。",
    "Students process information immediately instead of waiting until the end.": "让学习者在每一阶段即时消化信息。",
    "This made the learning experience more active and less like passive viewing.": "让学习体验更具主动参与性。",
    "Prototype Testing & Major Pivot": "原型测试与关键调整",
    "The major pivot was from long linear storytelling to micro-course modules with interaction after each segment, based on peer feedback and classroom-style review.": "根据同伴反馈与课堂式评审，方案从长篇线性叙事调整为分段微课，在每个模块后加入互动。",
    "Interactive Learning Module": "互动学习模块",
    "The tea bag module links cultural heritage with economies of scale and inclusive service innovation.": "茶包模块将文化遗产与规模经济、包容性服务创新连接起来。",
    "Potential Educational Value": "潜在教育价值",
    "Multi-Species / Biodiversity Clock, Scone Through Time, Ear Shield, SeedWalkers": "生物多样性时钟、司康时光、鲸声护盾、种子行者",
    "Creative Technology & Visual Practice, Independent 3D & AI Resource Platform, Machine Mapping, Codex / AI-assisted web prototype": "创意技术与视觉实践、独立 3D 与 AI 资源平台、机器映射、Codex / AI 辅助网页原型",
    "Scone Through Time, Cross-Culture Icebreaker, Biodiversity Clock": "司康时光、跨文化破冰包、生物多样性时钟",
    "Transformation design / Multi-species service": "转型设计 / 多物种服务",
    "Proof: systems framing, ecological research, phygital service prototype": "能力依据：系统构建、生态研究、实体与数字结合的服务原型",
    "Cultural service learning prototype": "文化服务学习原型",
    "Proof: research filtering, learning modules, testing-led pivot": "能力依据：研究筛选、学习模块设计、测试驱动的方案调整",
    "Independent 3D & AI resource platform": "独立 3D 与 AI 资源平台",
    "Proof: 381K+ views and 54K+ likes on one original Douyin Blender reel, 141K+ Bilibili views and 1.1K+ resource downloads / claims": "实践数据：单条抖音原创 Blender 视频获 38.1 万+播放、5.4 万+点赞；B 站累计 14.1 万+播放；资源下载 / 领取 1,100+ 次",
    "Environmental technology / Exhibition prototype": "环境技术 / 展览原型",
    "Proof: acoustic research, speculative system logic, physical computing": "能力依据：声学研究、概念系统构建、实体交互开发",
    "381K+ views": "38.1 万+ 播放",
    "A museum-and-park future experience that translates ecological rhythms into visitor noticing, reflection and action.": "连接博物馆与公园的未来体验，将生态节律转化为访客的观察、思考与行动。",
    "Capability proof: systems thinking, research translation, future prototyping, phygital service design.": "能力体现：系统思维、调研转化、未来体验原型、实体与数字结合的服务设计。",
    "Capability proof: research filtering, learning experience design, testing-led pivot, service innovation framing.": "能力体现：研究筛选、学习体验设计、测试驱动的方案调整、服务创新。",
    "Capability proof: tutorial production, public engagement, resource packaging, creator-platform operation.": "能力体现：教程制作、公众参与、资源打包、创作者平台运营。",
    "Capability proof: ecological research, bionic concept development, physical computing, public communication.": "能力体现：生态研究、仿生概念开发、实体交互、公共沟通。",
    "Capability proof: critical AI framing, interaction logic, data pipeline thinking, visual prototyping.": "能力体现：AI 批判性思考、交互逻辑、数据处理流程、视觉原型。",
    "Capability proof: service blueprinting, environmental research, spatial analysis, AR service flow.": "能力体现：服务蓝图、环境研究、空间分析、AR 服务流程。",
    "Capability proof: user research, persona synthesis, social design, game-based service prototyping.": "能力体现：用户研究、用户画像、社会设计、游戏化服务原型。",
    "01 / 3D Visualisation / Blender Craft": "01 / 三维可视化与 Blender 创作",
    "These videos show hands-on 3D craft rather than AI generation: modeling, lighting, material control, atmosphere and composition. They support the portfolio's creative technology direction by showing that I can make visual systems, not only describe them.": "这些视频展示手工三维创作：建模、灯光、材质控制、氛围与构图，体现从视觉构想到实际制作的能力。此部分作品并非 AI 生成。",
    "Manual 3D modeling": "手工三维建模",
    "Material atmosphere": "材质与氛围",
    "Cinematic atmosphere, material exploration and 3D composition.": "电影感氛围、材质探索与三维构图。",
    "02 / AI-assisted Web & Creative Pipeline": "02 / AI 辅助网页与创作流程",
    "This section separates AI-assisted workflow evidence from manual Blender craft. It includes an AI-assisted web prototype showcase and a Hyper3D collaboration video where the character and animation were generated through an AI-supported pipeline.": "此部分单独展示 AI 辅助工作流，包括网页原型，以及与 Hyper3D 合作的视频；其中角色与动画通过 AI 辅助流程生成。",
    "Hyper3D collaboration": "Hyper3D 合作项目",
    "AI-generated character": "AI 生成角色",
    "Creative workflow direction": "创作流程规划",
    "03 / Public Learning & Resource Platform": "03 / 公开教学与资源平台",
    "The resource platform turns Blender, 3D and AI-assisted design workflows into tutorials, visual work and downloadable resources across Douyin, Bilibili, Xiaohongshu and a personal resource website. It is shown as evidence of public-facing creative communication, not as a commercial product claim.": "资源平台将 Blender、三维与 AI 辅助设计流程转化为教程、视觉作品及可下载资源，发布于抖音、B 站、小红书与个人资源网站。这些数据体现公开创作与传播成果，不代表商业插件销量。",
    "381K+ views and 54K+ likes on one original Douyin Blender visual reel": "单条抖音原创 Blender 视觉视频：38.1 万+播放、5.4 万+点赞",
    "141K+ Bilibili views": "B 站累计 14.1 万+播放",
    "11.6K RED likes & collects": "小红书 1.16 万赞藏",
    "1.1K+ free resource downloads / claims": "免费资源下载 / 领取 1,100+ 次",
    "460+ resource users": "460+ 位资源用户",
    "54K+ likes on one original Douyin Blender visual reel": "单条抖音原创 Blender 视觉视频获 5.4 万+点赞",
    "I built a public-facing 3D and AI-assisted creative practice across Douyin, Xiaohongshu, Bilibili and a personal resource website. The practice translates Blender, GIS, AI-assisted workflows and visual prototyping processes into public tutorials, visual work, design-process content and reusable project resources.": "独立搭建覆盖抖音、小红书、B 站与个人资源网站的三维及 AI 辅助创作实践，将 Blender、GIS、AI 工作流与视觉原型制作转化为公开教程、视觉作品、设计过程内容及可复用项目资源。",
    "A self-initiated showcase of visual work created in Blender over two years.": "自主整理与发布两年间使用 Blender 创作的视觉作品。",
    "87 tutorial / design-process videos. Top educational video reached 23K+ views.": "发布 87 条教程 / 设计过程视频，播放最高的教学视频达 2.3 万+次。",
    "460+ resource users. Free Blender project files, 3D scene assets and workflow resources.": "覆盖 460+ 位资源用户，提供免费 Blender 工程文件、三维场景素材与工作流资源。",
    "Many learners struggle to understand 3D, Blender, GIS and AI-assisted workflows because tutorials often show final results without reusable files or workflow context. The challenge was to make complex technical workflows easier to learn, reproduce and adapt through public tutorials and downloadable project resources.": "许多教程只呈现最终效果，缺少可复用文件与完整流程，增加了三维、Blender、GIS 及 AI 辅助工作流的学习难度。因此，我通过公开教程与可下载工程资源，让复杂流程更易学习、复现和调整。",
    "Topic selection based on learner interest and workflow value": "结合学习者兴趣与工作流价值选择主题",
    "Blender / GIS / AI workflow testing and repeatable process design": "测试 Blender / GIS / AI 工作流，设计可复现流程",
    "Tutorial recording and design-process communication": "录制教程并讲解设计过程",
    "Project file packaging for reuse": "打包工程文件，支持重复使用",
    "Publishing visual work and design-process content across Douyin, Bilibili and Xiaohongshu / RED": "在抖音、B 站与小红书发布视觉作品及设计过程内容",
    "Free resource distribution through a personal resource website": "通过个人资源网站分发免费资源",
    "User questions, feedback and collaboration enquiries informing future content": "根据用户提问、反馈与合作咨询规划后续内容",
    "Explaining technical workflows in a format that can be watched, saved, repeated and shared by learners.": "以可观看、收藏、复现与分享的形式讲解技术工作流。",
    "Packaging project files so learners can study the workflow beyond the tutorial video.": "打包工程文件，让学习者在视频之外进一步研究完整工作流。",
    "Testing Blender, GIS and AI-assisted workflows as practical tools for visual and service design communication.": "测试 Blender、GIS 与 AI 辅助工作流在视觉及服务设计沟通中的实际用途。",
    "Building measurable public-facing practice outside a traditional internship or company project.": "通过独立实践积累可量化的公开创作与用户反馈。",
    "This independent practice has generated measurable public engagement, including 381K+ views and 54K+ likes on one original Douyin Blender visual reel, 141K+ Bilibili views, 11.6K Xiaohongshu likes and saves, and 1.1K+ free digital resource downloads / claims from 460+ users. It demonstrates my ability to create original 3D visual work, communicate complex Blender and AI-assisted workflows, design reusable digital resources and manage public-facing creative communication.": "这项独立实践积累了可量化的公开反馈：单条抖音原创 Blender 视觉视频获 38.1 万+播放与 5.4 万+点赞，B 站累计 14.1 万+播放，小红书 1.16 万赞藏，460+ 位用户累计下载 / 领取免费数字资源 1,100+ 次。体现了原创三维创作、复杂工作流讲解、可复用资源设计与公开内容运营能力。"
  });

  Object.assign(zh, {
    "Project case studies have moved.": "项目案例已迁移。",
    "The portfolio now uses a role-based Work page. If you are not redirected automatically, open the project hub below.": "作品集现已采用按能力方向组织的项目页面。如果未自动跳转，请通过下方链接打开项目列表。",
    "Open Work": "打开项目列表",
    "Primary navigation": "主导航",
    "Portfolio focus areas": "作品集方向",
    "Project filters": "项目筛选",
    "Project navigation": "项目导航",
    "Project section navigation": "项目章节导航",
    "Cyber Projection Toolkit running inside Blender": "Cyber Projection Toolkit 在 Blender 中的运行画面",
    "Cyber Projection Toolkit interface in Blender": "Cyber Projection Toolkit 的 Blender 操作界面",
    "Multi-Species Biodiversity Clock project board": "多物种生物多样性时钟项目展示板",
    "Multi-Species Biodiversity Clock cover": "多物种生物多样性时钟封面",
    "Scone Through Time project cover": "司康时光项目封面",
    "Scone Through Time cover": "司康时光封面",
    "Ear Shield project board": "鲸声护盾项目展示板",
    "Ear Shield cover": "鲸声护盾封面",
    "Machine Mapping cover": "机器映射封面",
    "SeedWalkers cover": "种子行者封面",
    "Cross-Culture Icebreaker cover": "跨文化破冰包封面",
    "Creative technology visual evidence": "创意技术视觉作品",
    "Portfolio visual evidence for public learning and resource platform work": "公开教学与资源平台的视觉实践成果",
    "Cyber Projection Toolkit controlling a holographic effect in Blender": "Cyber Projection Toolkit 在 Blender 中控制全息效果",
    "Cyber Projection Toolkit Blender feature demonstration": "Cyber Projection Toolkit 插件功能演示",
    "Create hologram from image or video control in Blender": "在 Blender 中通过图片或视频创建全息投影",
    "Automatically generated projection plane and material": "自动生成的投影平面与材质",
    "Cyber projection preset controls": "赛博投影预设控制",
    "Glitch animation controls inside the Blender add-on": "Blender 插件中的故障动画控制",
    "Colour and projection art direction controls": "色彩与投影视觉效果控制",
    "Replace current projection image or video": "替换当前投影的图片或视频",
    "Cyan hologram preset controlled through Cyber Projection Toolkit": "通过 Cyber Projection Toolkit 控制的青色全息预设",
    "Amber hologram preset controlled through Cyber Projection Toolkit": "通过 Cyber Projection Toolkit 控制的琥珀色全息预设",
    "Source video frame used to test the projection workflow": "用于测试投影流程的原始视频帧",
    "Making a duplicated hologram material independent": "将复制的全息材质设为独立材质",
    "Auto-Disconnect creating an independent hologram material": "使用自动断开功能创建独立全息材质",
    "Several independent cyber projection effects in one Blender scene": "同一 Blender 场景中的多个独立赛博投影效果",
    "Project slide asking what if the museum ran on ecological time, not human time": "项目命题：如果博物馆跟随生态时间运行",
    "Exterior of The Burrell Collection in Pollok Country Park": "波洛克乡村公园内的巴勒尔珍藏馆外景",
    "Pollok Country Park in Glasgow": "格拉斯哥波洛克乡村公园",
    "Biodiversity Clock case study sections": "生物多样性时钟项目章节",
    "AAD and desk research evidence slide": "动物辅助设计与案头调研展示板",
    "Field research findings slide": "实地调研发现展示板",
    "Stakeholder interview insight slide": "相关方访谈洞察展示板",
    "Design iteration slide showing prototypes and final biodiversity clock direction": "展示原型迭代及最终生物多样性时钟方向的设计板",
    "Final biodiversity clock interface and physical form": "最终生物多样性时钟界面与实体形态",
    "Seasonal and historical time interface designs": "季节与历史时间界面设计",
    "Interactive receipt specimen cards connecting animals and museum objects": "连接动物与博物馆藏品的互动票据样卡",
    "Storyboard showing visitor journey through the biodiversity clock experience": "生物多样性时钟访客体验旅程故事板",
    "Cross-Culture Icebreaker overview": "跨文化破冰包概览",
    "Cross-Culture case study sections": "跨文化破冰包项目章节",
    "Cross-Culture overview": "跨文化破冰包概览",
    "Cross-Culture research": "跨文化交流背景调研",
    "Cross-Culture user research": "跨文化交流用户研究",
    "Cross-Culture service system": "跨文化交流服务系统",
    "Cross-Culture user flows": "跨文化交流用户流程",
    "Cross-Culture final prototype": "跨文化破冰包最终原型",
    "Ear Shield project overview": "鲸声护盾项目概览",
    "Ear Shield case study sections": "鲸声护盾项目章节",
    "Ear Shield overview": "鲸声护盾概览",
    "Ear Shield background research": "鲸声护盾背景研究",
    "Ear Shield sound research": "鲸声护盾声音研究",
    "Ear Shield concept ideation": "鲸声护盾概念推演",
    "Ear Shield device system": "鲸声护盾设备系统",
    "Ear Shield interactive prototype": "鲸声护盾互动原型",
    "Ear Shield exhibition": "鲸声护盾展览现场",
    "Machine Mapping overview": "机器映射概览",
    "Machine Mapping project sections": "机器映射项目章节",
    "Machine Mapping research": "机器映射背景研究",
    "Machine Mapping learning loop": "机器映射学习循环",
    "Machine Mapping development": "机器映射设计开发",
    "Machine Mapping participant process": "机器映射参与者流程",
    "Machine Mapping implementation": "机器映射技术实现",
    "Scone Through Time case study sections": "司康时光项目章节",
    "Stakeholder source slide for Scone Through Time": "司康时光相关方研究展示板",
    "Core narrative timeline source slide": "核心叙事时间线研究材料",
    "Prototype testing source slide showing peer feedback and improvements": "包含同伴反馈与改进措施的原型测试展示板",
    "Animation module 1 source slide": "动画学习模块 1 展示板",
    "Animation module 2 source slide": "动画学习模块 2 展示板",
    "Animation module 3 source slide": "动画学习模块 3 展示板",
    "Interactive learning module source slide": "互动学习模块展示板",
    "SeedWalkers overview": "种子行者概览",
    "SeedWalkers case study sections": "种子行者项目章节",
    "SeedWalkers carbon background": "种子行者碳排放背景",
    "SeedWalkers biodiversity logic": "种子行者生物多样性逻辑",
    "SeedWalkers vegetation analysis": "种子行者植被分析",
    "SeedWalkers service framework": "种子行者服务框架",
    "SeedWalkers user journey": "种子行者用户旅程",
    "SeedWalkers service blueprint": "种子行者服务蓝图",
    "SeedWalkers implementation": "种子行者技术实现"
  });

  // Localise ordinary terminology even in earlier mixed-language translations.
  for (const key of Object.keys(zh)) {
    zh[key] = zh[key]
      .replace(/包容性 hospitality/gi, "包容性接待服务")
      .replace(/hospitality 学生/gi, "酒店与接待服务专业学生")
      .replace(/hospitality 学习者/gi, "酒店与接待服务专业学习者")
      .replace(/hospitality/gi, "酒店与接待服务")
      .replace(/ASN 学习者/g, "有额外学习支持需求的学习者")
      .replace(/中学 \/ ASN \/ /g, "中学生 / 需要额外学习支持者 / ")
      .replace(/Human-in-the-loop/g, "人在回路中参与反馈的")
      .replace(/Mel Spectrogram/g, "梅尔频谱")
      .replace(/Three Horizons/g, "三重视野（Three Horizons）")
      .replace(/Crazy 8s/g, "八格快速构思法（Crazy 8s）");
  }
  Object.assign(zh, {
    "A place-based experience innovation collaboration with Glasgow City Council and Glasgow Life.": "与格拉斯哥市议会及 Glasgow Life 开展的场地体验创新合作。",
    "Glasgow City Council × Glasgow Life": "格拉斯哥市议会 × Glasgow Life",
    "Pollok Country Park and The Burrell Collection, South Glasgow": "格拉斯哥南部的波洛克乡村公园与巴勒尔珍藏馆",
    "Developed in collaboration with The Burrell Collection and Pollok Country Park stakeholders, this place-based transformation design project translates ecological rhythms into a museum-and-park experience that invites visitors to notice, understand and participate in multi-species coexistence.": "与巴勒尔珍藏馆及波洛克乡村公园相关团队合作，将生态节律转化为连接博物馆与公园的体验，引导访客观察、理解并参与多物种共生。",
    "The Burrell Collection is a Glasgow Life museum located inside Pollok Country Park. The collaboration connected institutional priorities, visitor experience and the park's living ecology through meetings, field inquiry and service design.": "巴勒尔珍藏馆由 Glasgow Life 运营，坐落于波洛克乡村公园内。本次合作通过机构会议、实地调研与服务设计，将机构目标、访客体验和公园生态联系起来。",
    "A Glasgow Life museum embedded within Pollok Country Park. Photo: Anthony O'Neil / Geograph, CC BY-SA 2.0.": "位于波洛克乡村公园内、由 Glasgow Life 运营的博物馆。摄影：Anthony O'Neil / Geograph，CC BY-SA 2.0。",
    "Stakeholder meetings with The Burrell Collection and Pollok Country Park; field research; visitor and ecological inquiry.": "与巴勒尔珍藏馆、波洛克乡村公园相关方开展会议，并进行实地、访客与生态调研。",
    "A future museum-and-park experience translating ecological rhythms in Pollok Country Park into visitor action.": "连接博物馆与公园的未来体验，将波洛克乡村公园的生态节律转化为访客的观察、思考与行动。"
  });

  const zhTitles = {
    "index.html": "朱一帆 | 服务与转型设计作品集",
    "work.html": "朱一帆 | 项目",
    "practice.html": "朱一帆 | 创意技术与视觉实践",
    "about.html": "朱一帆 | 关于",
    "resource-platform.html": "朱一帆 | 独立 3D 与 AI 资源平台",
    "project-cyber-projection-toolkit.html": "朱一帆 | Cyber Projection Toolkit 商业 Blender 插件",
    "project-scone-through-time.html": "朱一帆 | 司康时光",
    "project-biodiversity-clock.html": "朱一帆 | 多物种 / 生物多样性时钟",
    "project-ear-shield.html": "朱一帆 | Ear Shield 鲸声护盾",
    "project-seedwalkers.html": "朱一帆 | SeedWalkers 种子行者",
    "project-machine-mapping.html": "朱一帆 | Machine Mapping 机器映射",
    "project-cross-culture.html": "朱一帆 | 跨文化破冰包"
  };

  const normalize = (value) => value.replace(/\s+/g, " ").trim();

  const getCurrentPage = () => {
    const page = window.location.pathname.split("/").pop();
    return page ? (page.includes(".") ? page : `${page}.html`) : "index.html";
  };

  const getInitialLanguage = () => {
    const params = new URLSearchParams(window.location.search);
    const queryLanguage = params.get("lang");
    if (queryLanguage === "zh" || queryLanguage === "en") return queryLanguage;

    let saved;
    try { saved = window.localStorage.getItem(LANGUAGE_KEY); } catch { /* Storage may be disabled. */ }
    if (saved === "zh" || saved === "en") return saved;

    const host = window.location.hostname.toLowerCase();
    return CHINESE_HOST_HINTS.some((hint) => host.includes(hint)) ? "zh" : "en";
  };

  const setTextNode = (node, value) => {
    const current = originalText.get(node) || node.nodeValue;
    const leading = current.match(/^\s*/)?.[0] || "";
    const trailing = current.match(/\s*$/)?.[0] || "";
    node.nodeValue = `${leading}${value}${trailing}`;
  };

  const applyLanguageToTextNodes = (language) => {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || SKIP_TAGS.has(parent.tagName) || parent.closest("[translate='no'], .language-switcher")) return NodeFilter.FILTER_REJECT;
        if (!normalize(node.nodeValue)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });

    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);

    nodes.forEach((node) => {
      if (!originalText.has(node)) originalText.set(node, node.nodeValue);
      const english = originalText.get(node);
      const key = normalize(english);
      if (language === "zh" && zh[key]) setTextNode(node, zh[key]);
      if (language === "en") node.nodeValue = english;
    });
  };

  const originalAttributes = new WeakMap();
  const applyLanguageToAttributes = (language) => {
    document.querySelectorAll("[aria-label], [alt], [title], [placeholder]").forEach((element) => {
      if (!originalAttributes.has(element)) {
        originalAttributes.set(element, Object.fromEntries(["aria-label", "alt", "title", "placeholder"]
          .filter((name) => element.hasAttribute(name)).map((name) => [name, element.getAttribute(name)])));
      }
      for (const [name, english] of Object.entries(originalAttributes.get(element))) {
        element.setAttribute(name, language === "zh" ? (zh[normalize(english)] || english) : english);
      }
    });
  };

  const updateLanguageLinks = (language) => {
    document.querySelectorAll("a[href]").forEach((link) => {
      const raw = link.getAttribute("href");
      if (!raw || raw.startsWith("#")) return;
      const url = new URL(raw, window.location.href);
      if (url.origin !== window.location.origin || !(/\.html$/.test(url.pathname) || !url.pathname.split("/").pop().includes("."))) return;
      url.searchParams.set("lang", language);
      link.setAttribute("href", `${url.pathname}${url.search}${url.hash}`);
    });
  };

  const updateSwitcherState = (language) => {
    document.querySelectorAll("[data-language-option]").forEach((button) => {
      const isActive = button.dataset.languageOption === language;
      button.classList.toggle("is-active", isActive);
      button.setAttribute("aria-pressed", String(isActive));
    });
  };

  const applyLanguage = (language) => {
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
    applyLanguageToTextNodes(language);
    applyLanguageToAttributes(language);
    updateLanguageLinks(language);
    document.title = language === "zh" && zhTitles[getCurrentPage()] ? zhTitles[getCurrentPage()] : originalTitle;
    updateSwitcherState(language);
  };

  const createLanguageSwitcher = () => {
    const nav = document.querySelector(".site-header nav");
    if (!nav || document.querySelector(".language-switcher")) return;

    const switcher = document.createElement("div");
    switcher.className = "language-switcher";
    switcher.setAttribute("aria-label", "Language switcher");

    [
      ["en", "EN"],
      ["zh", "中文"]
    ].forEach(([language, label]) => {
      const button = document.createElement("button");
      button.type = "button";
      button.textContent = label;
      button.dataset.languageOption = language;
      button.setAttribute("aria-pressed", "false");
      button.addEventListener("click", () => {
        try { window.localStorage.setItem(LANGUAGE_KEY, language); } catch { /* URL still preserves the choice. */ }
        const url = new URL(window.location.href);
        url.searchParams.set("lang", language);
        window.history.replaceState(null, "", url);
        applyLanguage(language);
      });
      switcher.appendChild(button);
    });

    nav.appendChild(switcher);
  };

  document.addEventListener("DOMContentLoaded", () => {
    createLanguageSwitcher();
    applyLanguage(getInitialLanguage());
  });
})();
